import { useMeasurementWorkspace } from '../../lib/measurements/store';
import type { ExecutionOptions } from '../../lib/measurements/execution';
import { MeasurementAnalysis } from './MeasurementAnalysis';
import type { ExecutionSummary } from '../../lib/measurements/execution';

export function ExecutionConfiguration({ value, change, disabled, workers, setWorkers, rounds }: {
  value: ExecutionOptions; change(value: ExecutionOptions): void; disabled: boolean; workers: number; setWorkers(value: number): void; rounds: number;
}) {
  const metrics = useMeasurementWorkspace(s => s.metrics);
  const patch = (next: Partial<ExecutionOptions>) => change({ ...value, ...next });
  return <details className="simulation-card execution-configuration" id="execution-configuration"><summary>Execution population · {value.regime === 'sessions' ? 'independent fixed-horizon sessions' : value.regime === 'persistent' ? 'one persistent trajectory' : 'independent paid rounds'}</summary>
    <fieldset className="measurement-form-grid" disabled={disabled}><label>Sampling engine<select aria-label="Sampling engine" value={value.samplingEngine ?? 'auto'} onChange={e => patch({ samplingEngine: e.target.value as ExecutionOptions['samplingEngine'] })}><option value="auto">Compiled plan when supported · automatic fallback</option><option value="reference">Canonical reference interpreter · cross-engine verification</option></select></label><label>Execution regime<select aria-label="Execution regime" value={value.regime} onChange={e => {
      const regime = e.target.value as ExecutionOptions['regime']; patch({ regime, ...(regime === 'independentRounds' ? { persistentKeys: [] } : {}) }); if (regime === 'persistent') setWorkers(1);
    }}><option value="independentRounds">Independent paid rounds · reset state</option><option value="persistent">Persistent state · single trajectory</option><option value="sessions">Independent sessions · reset between sessions</option></select></label>
    {value.regime !== 'independentRounds' && <label>State keys retained between paid rounds<input aria-label="Persistent state keys" value={value.persistentKeys.join(', ')} onChange={e => patch({ persistentKeys: e.target.value.split(',').map(k => k.trim()).filter(Boolean) })} placeholder="meter, collectionProgress, persistentWilds" /><small>Only these declared fields carry over. Other state resets every round. A graph that writes a retained field still controls its value.</small></label>}
    {value.regime === 'persistent' && <p>One trajectory uses one worker and one continuous random stream. Ordinary independent-round intervals are withheld when state is carried.</p>}
    {value.regime === 'sessions' && <><label>Paid rounds per session<input aria-label="Session horizon" type="number" min="1" max="65536" value={value.sessionLength} onChange={e => patch({ sessionLength: Number(e.target.value) })} /></label><label>Initial bankroll<input aria-label="Session bankroll" type="number" min="0" step="any" value={value.initialBankroll} onChange={e => patch({ initialBankroll: Number(e.target.value) })} /></label><label>External wager per round<input aria-label="Session wager" type="number" min="0.00000001" step="any" value={value.wager} onChange={e => patch({ wager: Number(e.target.value) })} /></label>
      <label>Feature activation used for session waits<select aria-label="Session feature activation" value={value.featureMetricId ?? ''} onChange={e => patch({ featureMetricId: e.target.value || null })}><option value="">No feature-wait tracking</option>{metrics.filter(m => m.options?.subject === 'round' && m.options.reduction === 'any' && ['event', 'count'].includes(m.options.source) || !m.nodeId && m.options?.subject === 'observation' && m.options.source === 'event').map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><small>Configure a Boolean event per complete paid round, or an any-event round reduction, in Track metric. Sessions without the feature are censored from its first-wait mean and remain in the feature-presence probability.</small></label>
      <p className="measurement-wide">{Number.isInteger(rounds / value.sessionLength) ? (rounds / value.sessionLength).toLocaleString() : 'Choose a whole number of'} independent sessions. Each session gets its own reproducible stream; worker count does not change it. Ruin records the first inability to fund the next wager. Sessions continue to the fixed horizon with hypothetical credit, preserving the population instead of excluding losing sessions.</p></>}
    <small>Selected workers: {workers}. Execution inputs are pinned with the graph and included in replay and saved evidence.</small></fieldset>
  </details>;
}
const sessionNames: Record<string, string> = { return: 'Session return / turnover', profit: 'Net session profit', profitable: 'Probability of a profitable session', endingBankroll: 'Ending bankroll', drawdown: 'Maximum drawdown', ruin: 'Ruin probability', ruinTime: 'First ruin time · ruined sessions only', duration: 'Session duration', drought: 'Longest zero-payout drought', extreme: 'Largest payout in a session', featureSeen: 'Probability of a feature within the horizon', featureWait: 'First feature wait · feature-seen sessions only' };
export function ExecutionReport({ value }: { value?: ExecutionSummary | null }) {
  if (!value) return null;
  return <section className="simulation-card execution-report" aria-label="Execution and session evidence"><div className="simulation-card-head"><div><h2>Exposure and session evidence</h2><p>{value.stateResetPolicy}</p></div><span>{value.regime} · {value.samplingEngine}</span></div>
    <dl className="tracked-statistics">{[['Attempted rounds', value.attemptedRounds], ['Completed rounds', value.completedRounds], ['Interrupted rounds', value.interruptedRounds], ['Cancelled / failed rounds', `${value.cancelledRounds} / ${value.failedRounds}`], ['Completed / interrupted sessions', `${value.completedSessions} / ${value.interruptedSessions}`]].map(([label, count]) => <div key={label}><dt>{label}</dt><dd>{typeof count === 'number' ? count.toLocaleString() : count}</dd></div>)}</dl>
    {value.carriesState && <p className="measurement-next-note">Paid rounds share retained state. Independent-round confidence intervals and acceptance verdicts are withheld. Session summaries use complete independent sessions.</p>}
    {!!value.loopTerminations?.length && <details className="loop-termination-evidence"><summary>Loop completion · {value.loopTerminations.length} observed loop points</summary>
      <p>Only loops in completed paid rounds contribute. The iteration limit is part of the authored bounded model. Reaching it does not establish termination of an uncapped feature or discarded probability mass. If a stop condition and the limit coincide, the limit takes precedence without evaluating the condition again.</p>
      {value.loopTerminationsComplete === false && <p role="alert">The loop-point budget was exceeded. These counts are partial; complete loop coverage is withheld.</p>}
      <div className="results-table-scroll"><table className="results-table"><thead><tr><th>Loop point</th><th>Completed invocations</th><th>Condition stops</th><th>Model-limit completions</th><th>Iteration min / mean / max</th></tr></thead><tbody>{value.loopTerminations.map(l => <tr key={l.nodeId}><td>{l.nodeId}</td><td>{l.completedInvocations.toLocaleString()}</td><td>{l.conditionCompletions.toLocaleString()}</td><td>{l.modelLimitCompletions.toLocaleString()}</td><td>{l.minimumIterations} / {(l.totalIterations / l.completedInvocations).toLocaleString(undefined, { maximumFractionDigits: 4 })} / {l.maximumIterations}</td></tr>)}</tbody></table></div>
    </details>}
    {value.regime === 'sessions' && <><p>{value.sessionPolicy}</p><div className="measurement-cards">{value.sessionMetrics.map(m => <article key={m.id} className="tracked-metric"><h3>{sessionNames[m.id.slice(8)] ?? m.id}</h3><p>{m.count.toLocaleString()} complete subjects · mean {m.mean?.toLocaleString(undefined, { maximumFractionDigits: 5 }) ?? '—'} · min {m.min ?? '—'} / max {m.max ?? '—'}</p><MeasurementAnalysis analysis={m.analysis} unit={['return', 'profitable', 'ruin', 'featureSeen'].includes(m.id.slice(8)) ? '' : ['ruinTime', 'duration', 'drought', 'featureWait'].includes(m.id.slice(8)) ? 'rounds' : 'payout units'} /></article>)}</div></>}
  </section>;
}
