import ExpressionTreeEditor from '../editor/ExpressionTreeEditor';
import { useState } from 'react';
import { parseExpression, type ExpressionAst } from '../../lib/expressionParser';
import { defaultOptions, type MeasurementOptions } from '../../lib/measurements/analysis';
import type { MetricDraft, MeasurementSchema } from '../../lib/measurements/model';

/** Semantics are saved in the plan; presentation can be changed independently during a run. */
export function MeasurementDesigner({ draft, schema, update }: { draft: MetricDraft; schema?: MeasurementSchema; update(patch: Partial<MetricDraft>): void }) {
  const options = draft.options;
  const patch = (value: Partial<MeasurementOptions>) => update({ options: { ...(options ?? defaultOptions()), ...value } });
  return <fieldset className="measurement-wide measurement-designer"><legend>Population, distribution and verification</legend>
    <label className="measurement-checkbox"><input type="checkbox" aria-label="Enable advanced measurement" checked={!!options} onChange={e => update({ options: e.target.checked ? defaultOptions() : undefined })} />Collect distributions and verification statistics</label>
    {options && <>
      <div className="measurement-form-grid"><label>Observation subject<select aria-label="Measurement subject" value={options.subject} onChange={e => patch({ subject: e.target.value as MeasurementOptions['subject'], independentSubjects: false, ...(e.target.value !== 'observation' ? { assertion: 'none' as const } : {}) })}>
        <option value="observation">One reveal / event / node visit</option><option value="round">Complete paid round · include absent-feature zeros</option><option value="episode">Complete feature episode</option><option value="transition">State transition · value at entry → value at exit</option></select></label>
      <label>Observed value<select aria-label="Measurement source" value={options.source} onChange={e => { const source = e.target.value as MeasurementOptions['source']; update({ options: { ...options, source }, ...(source === 'count' ? { valueMode: 'payout' as const } : source === 'event' ? { valueMode: 'expression' as const } : ['rawPayout', 'capDeduction', 'turnover', 'net'].includes(source) ? { nodeId: '', valueMode: 'payout' as const } : {}) }); }}>
        <option value="value">Numeric expression / settled payout</option><option value="event">Boolean event predicate · true = 1, false = 0</option><option value="count">Count visits · no expression needed</option><option value="rawPayout">Raw award before payout cap</option><option value="capDeduction">Amount removed by payout cap</option><option value="turnover">External wager / mode cost</option><option value="net">Settled payout minus external cost</option></select></label>
      {(options.subject === 'round' || options.subject === 'episode') && <label>Within each subject<select aria-label="Subject reduction" value={options.reduction} onChange={e => patch({ reduction: e.target.value as MeasurementOptions['reduction'] })}>{['sum', 'count', 'any', 'all', 'first', 'last', 'min', 'max', 'average', 'delta'].map(r => <option key={r}>{r}</option>)}</select></label>}
      {(options.subject === 'episode' || options.subject === 'transition') && <><Point label="Episode entry" value={options.entryNodeId} schema={schema} change={entryNodeId => patch({ entryNodeId })} /><Point label="Episode exit" value={options.exitNodeId} schema={schema} change={exitNodeId => patch({ exitNodeId })} /></>}
      <label>External cost · same units as payout<input aria-label="Measurement external cost" type="number" min="0.00000001" step="any" value={options.stake} onChange={e => patch({ stake: Number(e.target.value) })} /></label></div>
      <p className="measurement-next-note">A reveal mean, a bonus-total mean, and a return contribution use different populations. Round sums include zero when no child matches. Episode boundaries occur before the selected nodes execute. Each measurement’s external cost is separately pinned from the session wager; match them when estimating the same return.</p>
      <label className="measurement-checkbox"><input type="checkbox" aria-label="Assert exactly zero or false" checked={options.assertion === 'zero'} disabled={options.subject !== 'observation'} onChange={e => patch({ assertion: e.target.checked ? 'zero' : 'none' })} />Assert every valid value is exactly zero or false</label><small>Use a monetary residual or Boolean failure predicate at its authored boundary. Failures are counted before report conversion, with a bounded replayable witness. Invalid data prevents a clean result. Aggregated subjects cannot discard individual failures.</small>
      {(options.subject === 'episode' || options.subject === 'transition') && <details><summary>Entry cohort and completed-subject scope</summary><Expression label="Entry cohort predicate" value={options.entryFilter} change={entryFilter => patch({ entryFilter })} hint="Boolean predicate pinned at lifecycle entry. Excluded episodes are skipped without reading their child values." /><Expression label="Completed-subject predicate" value={options.exitFilter} change={exitFilter => patch({ exitFilter })} hint="Boolean predicate at the exit boundary, for example state.fsPlayed >= 20. The child scope remains separate." /></details>}
      <details><summary>Group, pair and award accounting</summary><div className="measurement-form-grid">
        <Expression label="Group / cohort key" value={options.group} change={group => patch({ group })} hint="state.fsType, state.fsIndex, or a scalar AST. Episode groups are pinned at entry." />
        <Expression label="Paired value / wager denominator" value={options.pair} change={pair => patch({ pair })} hint="Same subject as the primary value. Payout ÷ wager uses sums, with paired covariance." />
        <label>Paired value role<select aria-label="Paired value role" value={options.pairRole} onChange={e => patch({ pairRole: e.target.value as MeasurementOptions['pairRole'] })}><option value="value">Numeric value · covariance and paired difference</option><option value="wager">External wager · charged once at round completion</option></select><small>Wager expressions read completed-round state once, including rounds without the feature. Without an expression, external cost is used.</small></label>
        <Expression label="Unique award ID" value={options.awardId} change={awardId => patch({ awardId })} hint="A scalar authored by your graph. Reusing an ID in one paid round is reported as a duplicate." />
        <label>Maximum groups<input type="number" min="1" max="64" value={options.groupLimit} onChange={e => patch({ groupLimit: Number(e.target.value) })} /></label></div></details>
      <details><summary>Distribution and tail coverage</summary><div className="measurement-form-grid">
        <NumberList label="Fixed bin edges" value={options.binEdges} change={binEdges => patch({ binEdges })} />
        <NumberList label="Quantiles · probabilities" value={options.quantiles} change={quantiles => patch({ quantiles })} />
        <NumberList label="Payout tail thresholds" value={options.thresholds} change={thresholds => patch({ thresholds })} />
        <label>Maximum distinct payout values<input aria-label="Support limit" type="number" min="1" max="1024" value={options.supportLimit} onChange={e => patch({ supportLimit: Number(e.target.value) })} /></label></div><small>Each bin retains counts, payout sums and second moments. When the exact support exceeds the budget, fixed bins remain complete and quantiles become ranges.</small></details>
      <details><summary>Uncertainty, precision and reference checks</summary>
        <label className="measurement-checkbox"><input type="checkbox" aria-label="Independent measurement subjects" checked={options.independentSubjects} onChange={e => patch({ independentSubjects: e.target.checked })} />The model guarantees independent subjects</label>
        <label className="measurement-checkbox"><input type="checkbox" aria-label="Cluster measurement by paid round" checked={options.independentParents ?? false} onChange={e => patch({ independentParents: e.target.checked })} />Paid rounds are independent · cluster repeated observations within each round</label>
        <small>Repeated FS within one bonus usually share state. Use complete independent round or episode subjects for acceptance checks. Live fixed-count intervals are descriptive at repeated looks; bounded time-uniform intervals support repeated decisions.</small>
        <div className="measurement-form-grid"><OptionalNumber label="Reference mean" value={options.referenceMean} change={referenceMean => patch({ referenceMean })} /><OptionalNumber label="Acceptance tolerance" value={options.tolerance} change={tolerance => patch({ tolerance })} />
          <label>Reference statistic<select aria-label="Reference statistic" value={options.referenceStatistic} onChange={e => patch({ referenceStatistic: e.target.value as MeasurementOptions['referenceStatistic'] })}><option value="mean">Mean / importance-weighted mean</option><option value="ratio">Ratio of payout to paired denominator</option><option value="probability">Probability of a nonzero event</option></select></label>
          <OptionalNumber label="Proven minimum" value={options.lowerBound} change={lowerBound => patch({ lowerBound })} /><OptionalNumber label="Proven maximum" value={options.upperBound} change={upperBound => patch({ upperBound })} />
          <label>Confidence<input aria-label="Measurement confidence" type="number" step="0.001" min="0.501" max="0.999" value={options.confidence} onChange={e => patch({ confidence: Number(e.target.value) })} /></label>
          <label>Critical family size<input type="number" min="1" max="256" value={options.errorFamilySize} onChange={e => patch({ errorFamilySize: Number(e.target.value) })} /></label></div>
        <Reference value={options.referenceDistribution} change={referenceDistribution => patch({ referenceDistribution })} />
      </details>
      <details><summary>Ordered dependence and rare-event weighting</summary><NumberList label="Autocorrelation lags" value={options.lags} change={lags => patch({ lags })} /><small>Final summaries follow logical stream order, including gaps and streaks across chunk boundaries. Live unordered worker updates cannot establish sequence statistics.</small>
        <Expression label="Likelihood ratio weight" value={options.weight} change={weight => patch({ weight })} hint="Complete observation only. Supply the proven target/proposal likelihood ratio; forcing outcomes without valid weights cannot verify original RTP." /></details>
    </>}
  </fieldset>;
}
function Point({ label, value, schema, change }: { label: string; value?: string; schema?: MeasurementSchema; change(value: string): void }) {
  return <label>{label}<select aria-label={label} value={value ?? ''} onChange={e => change(e.target.value)} required><option value="">Choose an authored boundary…</option>{schema?.points.map(p => <option key={p.nodeId} value={p.nodeId}>{p.label} · {p.nodeId}</option>)}</select></label>;
}
function Expression({ label, value, change, hint }: { label: string; value?: ExpressionAst; change(value?: ExpressionAst): void; hint: string }) {
  const [text, setText] = useState(value ? JSON.stringify(value) : ''), [error, setError] = useState(''), [visual, setVisual] = useState(false);
  const commit = (ast?: ExpressionAst) => { change(ast); setText(ast ? JSON.stringify(ast) : ''); setError(''); };
  return <div className="measurement-expression"><label>{label}<select aria-label={`${label} editor`} value={visual ? 'visual' : 'text'} onChange={e => { if (error) return; setVisual(e.target.value === 'visual'); }}><option value="text">Expression text / AST</option><option value="visual">Visual typed expression</option></select></label>
    {visual ? value ? <ExpressionTreeEditor value={value} label={label} onChange={commit} allowSettlement /> : <button type="button" className="btn" onClick={() => commit({ exprType: 'fieldAccess', target: 'state', path: ['__choose_field__'] })}>Choose an authored field for {label}</button>
    : <textarea aria-label={label} rows={2} ref={element => element?.setCustomValidity(error)} value={text} onChange={e => { const source = e.target.value; setText(source); try { const ast = !source.trim() ? undefined : source.trim().startsWith('{') ? JSON.parse(source) : parseExpression(source); if (ast && typeof ast.exprType !== 'string') throw new Error('Use an expression or AST object.'); change(ast); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'Invalid expression.'); } }} aria-invalid={!!error} />}
    {value && <button type="button" className="btn sm" onClick={() => commit()}>Clear {label}</button>}<small>{hint}</small>{error && <span className="measurement-error">{error}</span>}
  </div>;
}
function NumberList({ label, value, change }: { label: string; value: number[]; change(value: number[]): void }) {
  const [text, setText] = useState(value.join(', '));
  const numbers = text.trim() ? text.split(',').map(x => Number(x.trim())) : []; const valid = numbers.every(Number.isFinite);
  return <label>{label}<input aria-label={label} ref={element => element?.setCustomValidity(valid ? '' : 'Enter comma-separated numbers.')} value={text} onChange={e => { setText(e.target.value); const values = e.target.value.trim() ? e.target.value.split(',').map(x => Number(x.trim())) : []; if (values.every(Number.isFinite)) change(values); }} aria-invalid={!valid} />{!valid && <span className="measurement-error">Enter comma-separated numbers.</span>}</label>;
}
function OptionalNumber({ label, value, change }: { label: string; value?: number; change(value?: number): void }) { return <label>{label}<input aria-label={label} type="number" step="any" value={value ?? ''} onChange={e => change(e.target.value === '' ? undefined : Number(e.target.value))} /></label>; }
function Reference({ value, change }: { value: MeasurementOptions['referenceDistribution']; change(value: MeasurementOptions['referenceDistribution']): void }) {
  const [rows, setRows] = useState(value.map(p => ({ value: String(p.value), probability: String(p.probability) })));
  const parsed = rows.map(r => ({ value: Number(r.value), probability: Number(r.probability) }));
  const valid = rows.every(r => r.value.trim() && r.probability.trim()) && parsed.every(p => Number.isFinite(p.value) && Number.isFinite(p.probability) && p.probability >= 0 && p.probability <= 1);
  const error = !valid ? 'Complete every finite outcome and probability.' : rows.length && (new Set(parsed.map(p => p.value)).size !== rows.length || Math.abs(parsed.reduce((s, p) => s + p.probability, 0) - 1) > 1e-10) ? 'Use distinct outcomes whose nonnegative probabilities sum to one.' : '';
  const update = (next: typeof rows) => { setRows(next); if (next.every(r => r.value.trim() && r.probability.trim() && Number.isFinite(Number(r.value)) && Number.isFinite(Number(r.probability)))) change(next.map(r => ({ value: Number(r.value), probability: Number(r.probability) }))); else if (!next.length) change([]); };
  return <div className="measurement-reference-editor"><strong>Independent reference PMF · optional</strong><div className="results-table-scroll"><table className="results-table"><thead><tr><th>Outcome</th><th>Probability</th><th /></tr></thead><tbody>{rows.map((row, i) => <tr key={i}><td><input aria-label={`Reference outcome ${i + 1}`} type="number" step="any" required value={row.value} ref={element => { if (i === 0) element?.setCustomValidity(error); }} onChange={e => update(rows.map((r, j) => j === i ? { ...r, value: e.target.value } : r))} /></td><td><input aria-label={`Reference probability ${i + 1}`} type="number" min="0" max="1" step="any" required value={row.probability} onChange={e => update(rows.map((r, j) => j === i ? { ...r, probability: e.target.value } : r))} /></td><td><button type="button" className="btn" onClick={() => update(rows.filter((_, j) => j !== i))}>Remove outcome {i + 1}</button></td></tr>)}</tbody></table></div><button type="button" className="btn" disabled={rows.length >= 1024} onClick={() => update([...rows, { value: '', probability: '' }])}>Add reference outcome</button>
    {error && <p className="measurement-error">{error}</p>}<small>Support, total variation, CDF distance and Pearson statistics compare the full distribution. Sparse expected counts require discrete null calibration. Prespecify the reference before inspecting the run.</small></div>;
}
