import { useState } from 'react';
import type { MeasurementAnalysis as Analysis, NumericInterval } from '../../lib/measurements/analysis';
import { formatNumber } from '../../lib/numberFormat';

const number = (value: number | null | undefined, digits = 5) => formatNumber(value, digits);
/** Shared live/final view. Every chart and test reads the same pinned, persisted statistics. */
export function MeasurementAnalysis({ analysis, unit }: { analysis?: Analysis | null; unit: string }) {
  const [tab, setTab] = useState('distribution'), [group, setGroup] = useState(''), [curve, setCurve] = useState('frequency');
  if (!analysis) return null;
  const data = group ? analysis.groups[group] ?? analysis : analysis;
  const turnover = data.normalization?.externalTurnover;
  return <div className="measurement-analysis">
    <div className="measurement-analysis-toolbar"><div role="tablist" aria-label="Measurement analysis">{['distribution', 'uncertainty', 'accounting', 'dependence'].map(id => <button type="button" key={id} role="tab" aria-selected={tab === id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{id}</button>)}</div>
      {Object.keys(analysis.groups).length > 0 && <label>Population<select aria-label="Analysis population" value={group} onChange={e => setGroup(e.target.value)}><option value="">All matching subjects</option>{Object.keys(analysis.groups).map(key => <option key={key}>{key}</option>)}</select></label>}</div>
    {group && <p>{number(data.count)} subjects · average {number(data.mean)} {unit} · min {number(data.min)} / max {number(data.max)}</p>}
    <div role="tabpanel" aria-label={`${tab} analysis`}>
    {data.interruptedLifecycle && data.interruptedLifecycle.cancelled.interruptedRounds + data.interruptedLifecycle.failed.interruptedRounds > 0 && <p role="status">Unfinished paid-round feature evidence is retained separately. Its partial values contribute to no payout statistics, reference verdicts or settled-round denominators.</p>}
    {data.assertion && <p role="status" className={`measurement-verdict ${data.assertion.status}`}>Exact zero / false assertion · {number(data.assertion.violations, 0)} violations / {number(data.assertion.checked, 0)} checked · {data.assertion.status.replace(/([A-Z])/g, ' $1')}. No observed violations describes the checked scope; invalid observations prevent a clean result.</p>}
    {data.weights && <p>Counts, quantiles and unweighted moments describe proposal observations. Target mean and event estimates use likelihood weights; distribution comparison uses the self-normalized weighted support and has no multinomial chi-square verdict.</p>}
    {analysis.groupsComplete === false && <p className="measurement-next-note">Group cardinality exceeded its bounded budget. Overall measurements remain complete; cohort results are withheld. Narrow the group key or increase its declared limit.</p>}
    {tab === 'distribution' && <><div className="measurement-analysis-toolbar"><span>{data.supportComplete ? `${data.support.length} exact empirical payout values` : 'Exact support budget reached · complete fixed bins retained'}</span><select aria-label="Distribution curve" value={curve} onChange={e => setCurve(e.target.value)}><option value="frequency">Frequency</option><option value="cdf">Cumulative probability · CDF</option><option value="survival">Survival · P(value ≥ threshold)</option><option value="return">{data.normalization ? 'Value / external turnover' : 'Value / subject'}</option></select></div>
      {curve === 'return' && data.normalization && <p>{number(data.normalization.paidRounds, 0)} settled paid parents · external turnover {number(turnover)}. {data.normalization.basis}</p>}
      <Distribution data={data} curve={curve} unit={unit} />
      <div className="measurement-quantiles">{data.quantiles.map(q => <div key={q.probability}><span>Q{number(q.probability * 100, 2)}</span><strong>{!data.count ? '—' : q.value != null ? number(q.value) : `[${q.lower == null ? '−∞' : number(q.lower)}, ${q.upper == null ? '+∞' : number(q.upper)})`}</strong><small>{q.method}</small></div>)}</div>
      <Table headers={['Tail ≥', 'Count', 'Probability', 'Payout sum', 'Conditional mean', 'First moment / all subjects', 'Second moment / all subjects', 'Contribution / external turnover']} rows={data.tails.map(t => [number(t.threshold), number(t.count), number(data.count ? t.probability : null), number(t.sum), number(t.mean), number(data.count ? t.sum / data.count : null), number(data.count ? t.secondMoment : null), number(turnover ? t.sum / turnover : null)])} />
      <details><summary>Expected upper-tail payout and return concentration</summary><Table headers={['Highest mass', 'Mean / mean bounds', 'Share of total payout', 'Method']} rows={data.upperTails.map(t => [number(t.tailMass), t.mean == null ? `[${number(t.lowerMean)}, ${number(t.upperMean)}]` : number(t.mean), `[${number(t.lowerReturnShare)}, ${number(t.upperReturnShare)}]`, t.method])} /></details>
      <details><summary>Counts and payout sums by fixed band</summary><Table headers={['Band', 'Count', 'Payout sum', 'Squared payout sum', 'Value / subject', 'Contribution / external turnover']} rows={data.bins.map(b => [`[${b.lower == null ? '−∞' : number(b.lower)}, ${b.upper == null ? '+∞' : number(b.upper)})`, number(b.count), number(b.sum), number(b.sumSquares), number(data.count ? b.sum / data.count : null), number(turnover ? b.sum / turnover : null)])} />{data.normalization && <p>{data.normalization.basis}</p>}</details>
      {data.comparison && <div className="measurement-reference"><strong>Independent distribution comparison</strong><p>Total variation {number(data.comparison.totalVariation)} · maximum CDF distance {number(data.comparison.cdfDistance)} · unexpected outcomes {number(data.comparison.unexpectedObservations)}</p><p>Pearson χ² {number(data.comparison.chiSquare)} / {data.comparison.degreesOfFreedom} df. p-value {number(data.comparison.pValue)}. {data.comparison.calibration}. A non-rejected null does not establish equivalence.</p></div>}
    </>}
    {tab === 'uncertainty' && <><p>{number(data.count)} matching subjects · SE {number(data.meanStandardError)} · estimated fixed-count sample requirement {number(data.requiredSampleSize, 0)}</p>
      <Interval label="Fixed-count mean" interval={data.meanInterval} /><Interval label="Nonzero-event probability" interval={data.probabilityInterval} /><Interval label="Time-uniform mean" interval={data.sequentialMeanInterval} />
      <Interval label="Mean with paid-round clustering" interval={data.clusteredMeanInterval} />
      <Interval label="Target mean with likelihood weighting" interval={data.weights?.ordinaryInterval} />
      <Interval label="Target event probability with likelihood weighting" interval={data.weights?.eventInterval} />
      <Interval label="Target return with weighted wagers" interval={data.weights?.pairedRatioInterval} />
      {!data.meanInterval && <p>Inference requires declared independence, sufficient valid observations and closed lifecycle boundaries. Event means remain descriptive when these assumptions are absent.</p>}
      {data.checks.length ? data.checks.map(check => <div className={`measurement-verdict ${check.status}`} key={check.id} role="status"><strong>{check.status.replace(/([A-Z])/g, ' $1')} · {check.id}</strong><p>Observed {number(check.observed)} · reference {number(check.reference)} · difference {number(check.difference)}</p><small>{check.detail}</small></div>) : <p>No acceptance rule configured. A descriptive statistic is not a verification pass.</p>}
    </>}
    {tab === 'accounting' && <><Table headers={['Accounting measure', 'Observed']} rows={[
      ['Subject / within-subject reduction', `${data.subject} / ${data.reduction}`],
      [data.parentExposure ? 'Paid rounds with matching children' : 'Distinct paid rounds · legacy exposure', number(data.parentExposure?.paidRoundsWithMatchingChildren ?? data.distinctParents)],
      ...(data.subject === 'episode' ? [['Owning feature episodes with matching children', number(data.parentExposure?.episodesWithMatchingChildren)]] : []),
      ['Feature entries / exits / unclosed', `${number(data.entries)} / ${number(data.exits)} / ${number(data.unclosedEpisodes)}`], ['Unique / duplicate award IDs', `${number(data.uniqueAwards)} / ${number(data.duplicateAwards)}`], ['Second moment', number(data.moments.secondMoment)], ['Population / sample variance', `${number(data.moments.populationVariance)} / ${number(data.moments.sampleVariance)}`], ['Moment skewness / excess kurtosis', `${number(data.moments.skewness)} / ${number(data.moments.excessKurtosis)}`], ['Mean absolute deviation', number(data.moments.meanAbsoluteDeviation)] ]} />
      {data.parentExposure && <p>Matching parent exposure counts accepted child observations before exit filtering and subject reduction. A real zero or false value still matches unless excluded by the child filter. Repeated children count their paid round and innermost owning episode once; nested ancestors do not inherit them. This exposure does not establish statistical independence.</p>}
      {['episode', 'transition'].includes(data.subject) && <>
        <p>{group ? 'Lifecycle counts follow the entry-selected cohort, including instances with no matching values or an excluded exit.' : 'Lifecycle counts include every authored entry before entry filtering.'} These counts use settled paid rounds. Open instances at completed settlement remain visible; unfinished-round boundaries appear separately below.</p>
        <p role={data.entries !== data.exits + data.unclosedEpisodes ? 'status' : undefined}>Lifecycle reconciliation · entries − exits − unclosed = {number(data.entries - data.exits - data.unclosedEpisodes)}. Matching value count can differ from lifecycle exposure.</p>
      </>}
      {data.interruptedLifecycle && <section aria-label="Interrupted feature lifecycle"><h4>Feature boundaries in unfinished paid rounds</h4>
        <Table headers={['Interruption', 'Paid rounds', 'Feature entries', 'Feature exits', 'Open at interruption', 'Tracking']} rows={Object.entries(data.interruptedLifecycle).map(([reason, counts]) => [reason, number(counts.interruptedRounds, 0), number(counts.entries, 0), number(counts.exits, 0), number(counts.openInstances, 0), counts.complete ? 'complete' : 'incomplete'])} />
        <p>Open instances are censored at interruption. A feature can reach its exit before the owning paid round fails; that exit remains boundary evidence and its numeric value is discarded. Cohorts follow the entry state.</p>
        {Object.values(data.interruptedLifecycle).some(counts => !counts.complete) && <p role="alert">A boundary mismatch or nesting limit prevented complete lifecycle tracking. These counts cannot establish full feature coverage.</p>}
      </section>}
      {data.weights && <><h4>Likelihood-weighted observations</h4><p>Ordinary importance estimate {number(data.weights.ordinaryEstimate)} · self-normalized estimate {number(data.weights.selfNormalizedEstimate)} · effective sample size {number(data.weights.effectiveSampleSize)}</p><p>Weight sum {number(data.weights.weightSum)} · weight range {number(data.weights.minWeight)}–{number(data.weights.maxWeight)}. These diagnostics cannot prove proposal coverage or validate an authored likelihood ratio.</p></>}
      <Interval label="Empirical absolute deviation bounds" interval={data.meanAbsoluteDeviationBounds} />
    </>}
    {tab === 'dependence' && <>{data.pair ? <><Table headers={['Paired statistic', 'Observed']} rows={[
      ['Paired subjects', number(data.pair.count)], ['Secondary sum / mean', `${number(data.pair.sumY)} / ${number(data.pair.meanY)}`], ['Covariance', number(data.pair.covariance)], ['Correlation', number(data.pair.correlation)], ['Ratio of sums', number(data.pair.ratio)], ['Mean paired difference', number(data.pair.meanDifference)], ['Secondary sample variance', number(data.pair.sampleVarianceY)], ['Variance of sum · includes covariance', number(data.pair.sampleVarianceSum)], ['Variance of paired difference', number(data.pair.sampleVarianceDifference)] ]} /><Interval label="Payout / denominator ratio" interval={data.pair.ratioInterval} /><Interval label="Paired difference" interval={data.pair.differenceInterval} />{data.pair.joint && <><p>{data.pair.joint.complete ? "Complete joint empirical support" : "Joint support budget exceeded"} · Pearson independence statistic {number(data.pair.joint.chiSquare)} · p-value {number(data.pair.joint.pValue)}.</p><small>{data.pair.joint.calibration}</small><Table headers={["Primary code", "Secondary code", "Count", "Joint probability"]} rows={data.pair.joint.support.map(p => [number(p.x), number(p.y), number(p.count), number(p.probability)])} /></>}</> : <p>Configure a paired value to measure component covariance or mixed-stake return.</p>}
      {data.subject === 'transition' && <><p>{data.transitionsComplete ? 'Complete observed transition matrix' : 'Transition support budget exceeded · matrix incomplete'}. Probabilities use the corresponding origin-state exposure.</p><Table headers={['From', 'To', 'Count', 'From-state exposure', 'Transition probability']} rows={data.transitions.map(t => [number(t.from), number(t.to), number(t.count), number(t.fromExposure), number(t.probability)])} /></>}
      {data.sequence ? data.sequence.ordered ? <><p>Longest nonzero-event streak {number(data.sequence.longestEventStreak)} · longest zero-event drought {number(data.sequence.longestDrought)} · mean completed gap {number(data.sequence.meanGap)} across {number(data.sequence.completedGaps)} gaps.</p><Table headers={['Logical lag', 'Autocorrelation']} rows={Object.entries(data.sequence.autocorrelations).map(([lag, value]) => [lag, number(value)])} /><p>Equal adjacent values {number(data.sequence.equalAdjacentPairs)} / {number(data.sequence.adjacentPairs)} adjacent pairs. {data.sequence.stateDwellComplete ? 'Complete interior-state dwell summary' : 'Dwell state budget exceeded'}.</p><Table headers={['State', 'Complete interior runs', 'Dwell observations', 'Mean length', 'Maximum length']} rows={data.sequence.stateDwell.map(s => [number(s.state), number(s.completedRuns), number(s.observations), number(s.meanLength), number(s.maximumLength)])} /><small>State dwells exclude the first and last censored runs. Gaps exclude leading and trailing censored waits. Correlation is descriptive evidence, not proof of RNG correctness.</small></> : <p role="status">Ordered statistics are pending a complete logical stream. Worker arrival order cannot define gaps, streaks or autocorrelation.</p> : <p>Select sequence lags to collect ordered gaps, streaks and autocorrelation.</p>}
    </>}
    </div>
  </div>;
}
function Interval({ label, interval }: { label: string; interval?: NumericInterval | null }) { return <div className="measurement-interval"><strong>{label}</strong><span>{interval ? `[${number(interval.lower)}, ${number(interval.upper)}]` : 'Undefined'}</span>{interval && <small>{interval.method} · {interval.assumptions}</small>}</div>; }
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) {
  const summary = headers.length === 2;
  return <><div className="results-table-scroll" tabIndex={summary ? undefined : 0} aria-label={summary ? undefined : `${headers[0]} table · scroll horizontally for more columns`}>
    <table className={`results-table${summary ? ' measurement-summary-table' : ''}`}><thead><tr>{headers.map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, i) => <td key={i}>{cell}</td>)}</tr>)}</tbody></table>
  </div>{!summary && <small className="measurement-scroll-note">Scroll horizontally to inspect every column.</small>}</>;
}
function Distribution({ data, curve, unit }: { data: Analysis; curve: string; unit: string }) {
  if (!data.count) return <p>No completed matching subjects to plot.</p>;
  const normalizer = data.normalization ? data.normalization.externalTurnover : data.count;
  if (curve === 'return' && !normalizer) return <p>External turnover is unavailable; contribution normalization is withheld.</p>;
  const bins = data.bins;
  const values = bins.map((bin, i) => { const before = bins.slice(0, i).reduce((sum, b) => sum + b.count, 0); return curve === 'cdf' ? (before + bin.count) / (data.count || 1) : curve === 'survival' ? 1 - before / (data.count || 1) : curve === 'return' ? bin.sum / normalizer! : bin.count / (data.count || 1); });
  const min = Math.min(0, ...values), max = Math.max(0.000001, ...values); const height = 140; const width = 640; const step = (width - 70) / bins.length; const y = (value: number) => 15 + (max - value) / (max - min) * (height - 40);
  return <figure className="measurement-distribution"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${curve} by payout band`}><line x1="45" x2={width - 15} y1={y(0)} y2={y(0)} stroke="currentColor" opacity="0.3" />{values.map((value, i) => <rect key={i} x={45 + i * step + 2} y={Math.min(y(value), y(0))} width={Math.max(1, step - 4)} height={Math.max(0.5, Math.abs(y(value) - y(0)))} fill="var(--accent, #55d8ba)"><title>{bins[i].lower ?? '−∞'} ≤ value &lt; {bins[i].upper ?? '+∞'}: {number(value)}</title></rect>)}<text x="0" y="18" fill="currentColor" fontSize="10">{number(max, 3)}</text><text x="0" y={height - 20} fill="currentColor" fontSize="10">{number(min, 3)}</text></svg><figcaption>{curve === 'return' ? data.normalization ? 'Value / external paid-round turnover' : `Value / subject (${unit})` : 'Probability'} · CDF counts values strictly below each upper edge; survival includes the lower edge · fixed semantic bands · hover a band for its exact value</figcaption></figure>;
}
