import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { metricRecipes, recipeDraft, type MetricRecipe } from '../../lib/measurements/recipes';
import type { MetricDraft } from '../../lib/measurements/model';
const actionNames = { measurement: 'Configure measurement', reference: 'Independent reference', execution: 'Execution population', results: 'Saved evidence / comparison', planning: 'Observation planning' };
export function MetricCatalogue({ configure, limitReached, runId }: { configure(value: MetricDraft): void; limitReached: boolean; runId?: string }) {
  const [search, setSearch] = useState(''), [family, setFamily] = useState(''), [selected, setSelected] = useState<MetricRecipe | null>(null);
  const recipes = useMemo(() => metricRecipes.filter(r => (!family || r.family === family) && `${r.name} ${r.id} ${r.definition}`.toLowerCase().includes(search.toLowerCase())), [search, family]);
  const jump = (id: string) => { const element = document.getElementById(id); if (element instanceof HTMLDetailsElement) element.open = true; element?.scrollIntoView({ behavior: 'smooth', block: 'start' }); (element?.querySelector('input, select, button') as HTMLElement | null)?.focus({ preventScroll: true }); };
  return <details className="simulation-card metric-catalogue" id="metric-catalogue"><summary>Metric catalogue · 159 definitions / 15 families</summary><p>Start from a verification question. Each recipe keeps its subject, units and prerequisites visible; configure the game-specific fields in the constructor’s measurement editor.</p>
    <div className="measurement-form-grid"><label>Find a metric<input aria-label="Search metric catalogue" value={search} onChange={e => setSearch(e.target.value)} placeholder="RTP, retrigger, covariance, ruin, pruned mass…" /></label><label>Family<select aria-label="Metric catalogue family" value={family} onChange={e => setFamily(e.target.value)}><option value="">All families</option>{[...new Map(metricRecipes.map(r => [r.family, r.familyName]))].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label></div>
    <div className="metric-catalogue-layout"><div className="metric-catalogue-list" aria-label="Metric definitions">{recipes.map(r => <button type="button" key={r.id} aria-pressed={selected?.id === r.id} onClick={() => setSelected(r)}><strong>{r.name}</strong><span>{r.familyName} · {r.priority}</span></button>)}{!recipes.length && <p>No matching definitions.</p>}</div>
      <article className="metric-recipe-detail">{selected ? <><span className="sim-eyebrow">{selected.id}</span><h3>{selected.name}</h3><p>{selected.definition}</p><dl><dt>Population</dt><dd>{selected.population}</dd><dt>Unit</dt><dd>{selected.unit}</dd><dt>Parameters</dt><dd>{selected.parameters.join(', ')}</dd></dl><p className="measurement-next-note">{selected.prerequisite}</p>
        {selected.action === 'measurement' ? <button type="button" className="btn primary" disabled={limitReached} onClick={() => configure(recipeDraft(selected))}>{actionNames.measurement} →</button> : selected.action === 'results' ? <Link className="btn primary" to={runId ? `/results?run=${runId}` : '/results'}>{actionNames.results} →</Link> : <button type="button" className="btn primary" onClick={() => jump(selected.action === 'reference' ? 'reference-workbench' : selected.action === 'planning' ? 'sample-planning' : 'execution-configuration')}>{actionNames[selected.action]} →</button>}
        <small>Definitions describe the verification requirement. A configured measurement or calculator output becomes evidence only with its declared inputs, scope and assumptions.</small></> : <p>Select a definition to see what it measures and how to configure it.</p>}</article></div>
  </details>;
}
