import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { metricRecipes, recipeDraft, type MetricRecipe } from '../../lib/measurements/recipes';
import type { MetricDraft } from '../../lib/measurements/model';
const actionNames = { measurement: 'Configure measurement', accounting: 'Configure component accounting', profile: 'Configure verification profile', reference: 'Independent reference', execution: 'Execution population', results: 'Saved evidence / comparison', planning: 'Observation planning' };
const availabilityNames = { ready: 'Native workflow', authored: 'Requires an authored game contract', partial: 'Partial workflow' };
export function MetricCatalogue({ configure, accounting, profile, limitReached, runId }: { configure(value: MetricDraft): void; accounting(): void; profile(): void; limitReached: boolean; runId?: string }) {
  const [search, setSearch] = useState(''), [family, setFamily] = useState(''), [availability, setAvailability] = useState(''), [selected, setSelected] = useState<MetricRecipe | null>(null);
  const recipes = useMemo(() => metricRecipes.filter(r => (!family || r.family === family) && (!availability || r.availability === availability) && `${r.name} ${r.id} ${r.definition} ${r.implementationScope}`.toLowerCase().includes(search.toLowerCase())), [search, family, availability]);
  const nativeTools: Record<string, string> = { 'mechanics.strategy': 'experiments', 'comparison.sensitivity': 'experiments', 'bounds.loop_termination': 'resource', 'bounds.weight_diagnostics': 'sampling', 'bounds.weighted_estimate': 'sampling', 'provenance.identity': 'inputs' };
  const jump = (id: string) => { const element = document.getElementById(id); for (let parent = element; parent; parent = parent.parentElement) if (parent instanceof HTMLDetailsElement) parent.open = true; element?.scrollIntoView({ behavior: 'smooth', block: 'start' }); (element?.querySelector('input, select, button') as HTMLElement | null)?.focus({ preventScroll: true }); };
  return <details className="simulation-card metric-catalogue" id="metric-catalogue"><summary>Metric catalogue · 159 definitions / 15 families</summary><p>Start from a verification question. Each recipe keeps its subject, units and prerequisites visible; configure the game-specific fields in the constructor’s measurement editor.</p>
    <div className="measurement-form-grid"><label>Find a metric<input aria-label="Search metric catalogue" value={search} onChange={e => setSearch(e.target.value)} placeholder="RTP, retrigger, covariance, ruin, pruned mass…" /></label><label>Family<select aria-label="Metric catalogue family" value={family} onChange={e => setFamily(e.target.value)}><option value="">All families</option>{[...new Map(metricRecipes.map(r => [r.family, r.familyName]))].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Workflow coverage<select aria-label="Metric workflow coverage" value={availability} onChange={e => setAvailability(e.target.value)}><option value="">All reviewed definitions</option>{Object.entries(availabilityNames).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label></div>
    <div className="metric-catalogue-layout"><div className="metric-catalogue-list" aria-label="Metric definitions">{recipes.map(r => <button type="button" key={r.id} aria-pressed={selected?.id === r.id} onClick={() => setSelected(r)}><strong>{r.name}</strong><span>{r.familyName} · {r.priority} · {availabilityNames[r.availability]}</span></button>)}{!recipes.length && <p>No matching definitions.</p>}</div>
      <article className="metric-recipe-detail">{selected ? <><span className="sim-eyebrow">{selected.id}</span><h3>{selected.name}</h3><p>{selected.definition}</p><dl><dt>Population</dt><dd>{selected.population}</dd><dt>Unit</dt><dd>{selected.unit}</dd><dt>Parameters</dt><dd>{selected.parameters.join(', ')}</dd></dl><p className="measurement-next-note">{selected.prerequisite}</p><div className={`measurement-coverage ${selected.availability}`}><strong>{availabilityNames[selected.availability]}</strong><p>{selected.implementationScope}</p></div>
        {nativeTools[selected.id] ? <button type="button" className="btn primary" disabled={!runId} onClick={() => { window.dispatchEvent(new CustomEvent('slotmath:verification-tab', { detail: nativeTools[selected.id] })); jump('verification-workbench'); }}>Open verification experiments →</button> : selected.action === 'profile' ? <button type="button" className="btn primary" onClick={profile}>{actionNames.profile} →</button> : selected.action === 'accounting' ? <button type="button" className="btn primary" disabled={limitReached} onClick={accounting}>{actionNames.accounting} →</button> : selected.action === 'measurement' ? <button type="button" className="btn primary" disabled={limitReached} onClick={() => configure(recipeDraft(selected))}>{actionNames.measurement} →</button> : selected.action === 'results' ? <Link className="btn primary" to={runId ? `/results?run=${runId}` : '/results'}>{actionNames.results} →</Link> : <button type="button" className="btn primary" onClick={() => jump(selected.id === 'comparison.exact_support' ? 'exact-law-comparison' : selected.action === 'reference' ? 'reference-workbench' : selected.action === 'planning' ? 'sample-planning' : 'execution-configuration')}>{actionNames[selected.action]} →</button>}
        {nativeTools[selected.id] && !runId && <p>Complete and select a baseline run to pin the experiment inputs.</p>}<small>Definitions describe the verification requirement. A configured measurement or calculator output becomes evidence only with its declared inputs, scope and assumptions.</small></> : <p>Select a definition to see what it measures and how to configure it.</p>}</article></div>
  </details>;
}
