import { useEffect, useRef, useState } from 'react';
import { calculationRequest } from '../../lib/measurements/requests';

interface Outcome { value: string; probability: string }
interface Bounds { lower: string; upper: string | null }
interface FiniteReport { provenance: string; retainedMass: string; prunedMass: string; cost: string; mean: Bounds; rtp: Bounds; secondMoment: Bounds; variance: Bounds; hitProbability: Bounds; houseEdge: string | null; maximumKnownOutcome: string; provenMaximum: string | null; skewness: string | null; excessKurtosis: string | null; assumptions: string }
interface MarkovReport { absorptionProbability: string | null; durationSecondMoment: string | null; durationVariance: string | null; stationaryOccupancy: string[] | null; longRunRewardPerStep: string | null; longRunCostPerStep: string | null; longRunReturn: string | null; status: string; expectedVisits: string[]; expectedDuration: string | null; expectedReward: string | null; reachableStates: number[]; detail: string }
interface Workbench { outcomes: Outcome[]; cost: string; prunedMass: string; cap: string; matrix: string[][]; rewards: string[]; initial: number; costs?: string[] }
const initial = (): Workbench => ({ outcomes: [{ value: '0', probability: '1/2' }, { value: '1.96', probability: '1/2' }], cost: '1', prunedMass: '0', cap: '', matrix: [['1/2', '1/2'], ['0', '0']], rewards: ['1', '4'], initial: 0 });
function restore(): Workbench {
  try {
    const value = JSON.parse(localStorage.getItem('slotmath-reference-workbench-v1') ?? 'null');
    const string = (v: unknown) => typeof v === 'string' && v.length <= 80;
    if (value && Array.isArray(value.outcomes) && value.outcomes.length > 0 && value.outcomes.length <= 128 && value.outcomes.every((r: Outcome) => r && string(r.value) && string(r.probability))
      && [value.cost, value.prunedMass, value.cap].every(string) && Array.isArray(value.matrix) && value.matrix.length > 0 && value.matrix.length <= 16 && value.matrix.every((r: unknown[]) => Array.isArray(r) && r.length === value.matrix.length && r.every(string))
      && Array.isArray(value.rewards) && value.rewards.length === value.matrix.length && value.rewards.every(string) && (value.costs === undefined || Array.isArray(value.costs) && value.costs.length === value.matrix.length && value.costs.every(string))
      && Number.isInteger(value.initial) && value.initial >= 0 && value.initial < value.matrix.length) return value;
  } catch { /* recover local draft */ }
  return initial();
}

/** Independent authorable references; never substitutes its result for the observed graph. */
export function ReferenceWorkbench({ runId }: { runId?: string }) {
  const [draft, setDraft] = useState(restore), [kind, setKind] = useState('distribution'), [busy, setBusy] = useState(false), [error, setError] = useState(''), [status, setStatus] = useState('');
  const [result, setResult] = useState<{ input: unknown; report: FiniteReport | MarkovReport; retention?: { retained: boolean; note: string } } | null>(null);
  const change = (patch: Partial<Workbench>) => { const next = { ...draft, ...patch }; setDraft(next); setResult(null); setError(''); try { localStorage.setItem('slotmath-reference-workbench-v1', JSON.stringify(next)); } catch { /* tab draft stays usable */ } };
  const controller = useRef<AbortController | null>(null);
  useEffect(() => () => controller.current?.abort(), []);
  return <section className="measurement-workspace reference-workbench" aria-label="Independent mathematical references"><details id="reference-workbench"><summary><strong>Independent reference workbench</strong> · exact probability laws, pruning bounds and finite-state features</summary>
    <p>Build a small model independently of the production graph. Rational inputs preserve exact probabilities and rewards. A supplied model verifies its own assumptions; compare it with the corresponding graph measurement.</p>
    {runId && <p>Calculations will be retained as independently authored references for run <code>{runId}</code>. Check their assumptions against its pinned graph.</p>}
    <div className="measurement-analysis-toolbar"><label>Reference model<select aria-label="Reference model type" disabled={busy} value={kind} onChange={e => { setKind(e.target.value); setResult(null); setError(''); }}><option value="distribution">Finite payout distribution</option><option value="markov">Absorbing state / reward model</option><option value="stationary">Stationary occupation / persistent return</option></select></label>
      <button className="btn" onClick={() => change(kind === 'stationary' ? { ...initial(), matrix: [['1/2', '1/2'], ['1/4', '3/4']], rewards: ['0', '1.47'], costs: ['1', '1'] } : initial())} disabled={busy}>Load independent example</button></div>
    <form onSubmit={async e => { e.preventDefault(); controller.current = new AbortController(); setBusy(true); setError(''); setResult(null); const input = kind === 'distribution' ? { outcomes: draft.outcomes, cost: draft.cost, prunedMass: draft.prunedMass, provenMaximum: draft.cap || null } : { transientMatrix: draft.matrix, rewards: draft.rewards, initialState: draft.initial, stationary: kind === 'stationary', costs: draft.costs ?? draft.rewards.map(() => '1') }; try {
      const endpoint = `/api/runs/${runId ? `${encodeURIComponent(runId)}/` : ''}measurements/reference/${kind === 'stationary' ? 'markov' : kind}`;
      if (runId) {
        const body = await calculationRequest<{ runId: string; report: FiniteReport | MarkovReport; retention: { retained: boolean; note: string } }>(endpoint, input, controller.current!.signal, setStatus, 15000);
        if (body.runId !== runId) throw new Error('Retained reference belongs to a different run.');
        setResult({ input, report: body.report, retention: body.retention });
      } else setResult({ input, report: await calculationRequest<FiniteReport | MarkovReport>(endpoint, input, controller.current!.signal, setStatus, 15000) });
    } catch (err) { setError(err instanceof Error ? err.message : 'Reference calculation failed.'); } finally { setBusy(false); } }}>
      <fieldset disabled={busy} className="measurement-reference-fields">
      {kind === 'distribution' ? <><div className="results-table-scroll"><table className="results-table"><thead><tr><th>Settled payout</th><th>Exact probability</th><th /></tr></thead><tbody>{draft.outcomes.map((outcome, i) => <tr key={i}><td><input aria-label={`Outcome ${i + 1} payout`} maxLength={80} required value={outcome.value} onChange={e => change({ outcomes: draft.outcomes.map((o, j) => j === i ? { ...o, value: e.target.value } : o) })} /></td><td><input aria-label={`Outcome ${i + 1} probability`} maxLength={80} required value={outcome.probability} onChange={e => change({ outcomes: draft.outcomes.map((o, j) => j === i ? { ...o, probability: e.target.value } : o) })} /></td><td><button type="button" className="btn" disabled={draft.outcomes.length === 1} onClick={() => change({ outcomes: draft.outcomes.filter((_, j) => i !== j) })}>Remove</button></td></tr>)}</tbody></table></div><button type="button" className="btn" disabled={draft.outcomes.length >= 128} onClick={() => change({ outcomes: [...draft.outcomes, { value: '', probability: '' }] })}>Add outcome</button>
        <div className="measurement-form-grid"><label>External mode cost<input aria-label="Reference external cost" maxLength={80} required value={draft.cost} onChange={e => change({ cost: e.target.value })} /></label><label>Unresolved probability mass<input aria-label="Reference pruned mass" maxLength={80} required value={draft.prunedMass} onChange={e => change({ prunedMass: e.target.value })} /></label><label>Proven maximum · optional<input aria-label="Reference proven maximum" maxLength={80} value={draft.cap} onChange={e => change({ cap: e.target.value })} /></label></div><small>Retained probability + unresolved mass must equal 1 exactly. Use integers, decimals or fractions such as 1/1000. No finite upper bound is claimed for unresolved payout mass without a proven maximum.</small></>
      : <><div className="results-table-scroll"><table className="results-table"><thead><tr><th>From / to</th>{draft.matrix.map((_, i) => <th key={i}>State {i}</th>)}<th>Reward per visit</th>{kind === 'stationary' && <th>External cost / step</th>}</tr></thead><tbody>{draft.matrix.map((row, i) => <tr key={i}><th>State {i}</th>{row.map((cell, j) => <td key={j}><input aria-label={`Transition ${i} to ${j}`} maxLength={80} required value={cell} onChange={e => change({ matrix: draft.matrix.map((r, k) => k === i ? r.map((v, l) => l === j ? e.target.value : v) : r) })} /></td>)}<td><input aria-label={`State ${i} reward`} maxLength={80} required value={draft.rewards[i]} onChange={e => change({ rewards: draft.rewards.map((r, j) => j === i ? e.target.value : r) })} /></td>{kind === 'stationary' && <td><input aria-label={`State ${i} cost`} maxLength={80} required value={draft.costs?.[i] ?? '1'} onChange={e => change({ costs: draft.rewards.map((_, j) => j === i ? e.target.value : draft.costs?.[j] ?? '1') })} /></td>}</tr>)}</tbody></table></div><div className="measurement-analysis-toolbar"><button type="button" className="btn" disabled={draft.matrix.length >= 16} onClick={() => change({ matrix: [...draft.matrix.map(row => [...row, '0']), Array(draft.matrix.length + 1).fill('0')], rewards: [...draft.rewards, '0'], costs: [...(draft.costs ?? draft.rewards.map(() => '1')), '1'] })}>Add state</button><button type="button" className="btn" disabled={draft.matrix.length === 1} onClick={() => change({ matrix: draft.matrix.slice(0, -1).map(row => row.slice(0, -1)), rewards: draft.rewards.slice(0, -1), costs: draft.costs?.slice(0, -1), initial: Math.min(draft.initial, draft.matrix.length - 2) })}>Remove last state</button><label>Initial state<select aria-label="Reference initial state" value={draft.initial} onChange={e => change({ initial: Number(e.target.value) })}>{draft.matrix.map((_, i) => <option key={i} value={i}>State {i}</option>)}</select></label></div><small>{kind === 'stationary' ? 'Stationary rows must sum exactly to 1. Supply payout reward and positive external cost per step. A unique reachable recurrent class is required; periodic chains describe occupation averages. ' : ''}Rows contain transient transition probabilities. Missing probability absorbs. Reward is credited once per state visit. A reachable non-absorbing class is reported without a finite duration or reward.</small></>}
      <button type="submit" className="btn primary">{busy ? 'Calculating…' : 'Calculate exact reference'}</button></fieldset>
    </form>
    {busy && <p role="status">{status} <button type="button" className="btn" onClick={() => controller.current?.abort()}>Cancel calculation</button></p>}
    {error && <p role="alert" className="measurement-error">{error}</p>}
    {result && <div className="measurement-reference" aria-label="Reference calculation result">{'rtp' in result.report ? <><h3>{result.report.provenance}</h3><dl className="tracked-statistics">{(['mean', 'rtp', 'secondMoment', 'variance', 'hitProbability'] as const).map(key => { const b = (result.report as FiniteReport)[key]; return <div key={key}><dt>{key}</dt><dd>{b.upper === b.lower ? b.lower : `[${b.lower}, ${b.upper ?? 'unbounded'}]`}</dd></div>; })}</dl><p>Retained mass {result.report.retainedMass} · unresolved mass {result.report.prunedMass} · maximum known outcome {result.report.maximumKnownOutcome} · proven maximum {result.report.provenMaximum ?? 'unavailable'} · house edge {result.report.houseEdge ?? 'withheld · incomplete mean'}</p><small>{result.report.assumptions}</small></> : <><h3>{result.report.status}</h3><p>Absorption probability {result.report.absorptionProbability ?? 'not applicable'} · stationary occupation {result.report.stationaryOccupancy?.join(', ') ?? 'not applicable'}</p><p>Expected visits: {result.report.expectedVisits.join(', ')}</p><p>Expected duration {result.report.expectedDuration ?? 'undefined'} · expected reward {result.report.expectedReward ?? 'undefined'}</p><p>Duration second moment / variance {result.report.durationSecondMoment ?? 'undefined'} / {result.report.durationVariance ?? 'undefined'} · long-run reward / cost {result.report.longRunRewardPerStep ?? 'undefined'} / {result.report.longRunCostPerStep ?? 'undefined'} · return {result.report.longRunReturn ?? 'undefined'}</p><small>{result.report.detail}</small></>}
      {result.retention && <p role="status">{result.retention.note}</p>}
      <details><summary>Authored input and exact result</summary><pre>{JSON.stringify(result, null, 2)}</pre></details><button className="btn" onClick={() => { const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `slotmath-${kind}-reference.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}>Export reference evidence</button></div>}
  </details></section>;
}
