import { useEffect, useRef, useState } from 'react';
import { calculationRequest } from '../../lib/measurements/requests';
import { downloadReport } from '../../lib/results/export';
interface Plan { allocatedAlpha: number; normalCritical: number; approximateMeanRounds: number | null; timeUniformBoundedMeanRounds: number | null; eventDetectionRounds: number | null; zeroObservedEventUpper: number; meanBudgetSufficient: boolean | null; detectionBudgetSufficient: boolean | null; assumptions: string; authoredInputSha256: string }
export function SamplePlanning() {
  const [values, setValues] = useState({ confidence: '.95', errorFamilySize: '1', precision: '.001', variance: '', lowerBound: '', upperBound: '', eventProbability: '0.0000001', detectionPower: '.95', roundBudget: '100000' });
  const [report, setReport] = useState<Plan | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [status, setStatus] = useState('');
  const controller = useRef<AbortController | null>(null);
  useEffect(() => () => controller.current?.abort(), []);
  return <details id="sample-planning" className="simulation-card"><summary>Plan sufficient observations · precision, rare events and repeated monitoring</summary>
    <p>Set the independent subject before choosing a round budget. Rare-event detection and return precision answer different questions. Feature reveals from one paid round cannot be counted as independent trials without a model guarantee.</p>
    <form onSubmit={async e => { e.preventDefault(); controller.current = new AbortController(); setBusy(true); setReport(null); setError(''); const input = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, value === '' ? null : Number(value)]));
      try { const body = await calculationRequest<Plan>('/api/runs/measurements/reference/planning', input, controller.current!.signal, setStatus, 15000); setReport(body); }
      catch (err) { setError(err instanceof Error ? err.message : 'Planning failed.'); } finally { setBusy(false); }
    }}><fieldset className="measurement-form-grid" disabled={busy}>{([['confidence', 'Family confidence'], ['errorFamilySize', 'Number of comparisons'], ['precision', 'Absolute mean precision · value units'], ['variance', 'Independent reference / pilot variance · optional'], ['lowerBound', 'Proven lower support · optional'], ['upperBound', 'Proven upper support · optional'], ['eventProbability', 'Rare-event probability · optional'], ['detectionPower', 'Probability of detecting at least one event'], ['roundBudget', 'Independent subject budget']] as const).map(([key, label]) => <label key={key}>{label}<input aria-label={`Planning ${key}`} type="number" step="any" value={values[key]} onChange={e => { setValues(v => ({ ...v, [key]: e.target.value })); setReport(null); }} /></label>)}<button type="submit" className="btn primary">{busy ? 'Calculating…' : 'Calculate observation budget'}</button></fieldset></form>
    {busy && <p role="status">{status} <button type="button" className="btn" onClick={() => controller.current?.abort()}>Cancel calculation</button></p>}
    {error && <p role="alert" className="measurement-error">{error}</p>}
    {report && <div aria-label="Observation planning result"><dl className="tracked-statistics">{[['Allocated alpha', report.allocatedAlpha], ['Approximate mean subjects', report.approximateMeanRounds], ['Bounded time-uniform mean subjects', report.timeUniformBoundedMeanRounds], ['Subjects to detect at least one event', report.eventDetectionRounds], ['Zero-event one-sided upper bound at budget', report.zeroObservedEventUpper]].map(([name, value]) => <div key={String(name)}><dt>{name}</dt><dd>{typeof value === 'number' ? value.toLocaleString(undefined, { maximumSignificantDigits: 10 }) : 'Insufficient inputs / planning limit'}</dd></div>)}</dl><p>Mean budget: {report.meanBudgetSufficient == null ? 'unresolved' : report.meanBudgetSufficient ? 'sufficient under declared method' : 'insufficient'} · detection budget: {report.detectionBudgetSufficient == null ? 'unresolved' : report.detectionBudgetSufficient ? 'sufficient' : 'insufficient'}.</p><small>{report.assumptions}</small><p className="measurement-fingerprint">Input SHA-256 <code>{report.authoredInputSha256}</code></p><button type="button" className="btn" onClick={() => downloadReport('slotmath-sample-plan.json', JSON.stringify({ input: values, report }, null, 2), 'application/json')}>Export observation plan</button></div>}
  </details>;
}
