import { useEffect, useRef, useState } from 'react';
import type { RunSnapshot } from '../../lib/realtime/runProtocol';
import type { ExecutionOptions } from '../../lib/measurements/execution';
import type { NumericInterval } from '../../lib/measurements/analysis';
import type { EvidenceInput } from '../editor/EvidenceInputsEditor';
import { calculationRequest } from '../../lib/measurements/requests';
import { formatNumber } from '../../lib/numberFormat';

interface GraphInput { initialState?: Record<string, unknown>; nodes: { id: string; label?: string; nodeType: string; winCap?: number; maxIterations?: number; drawWeights?: { outcomeId: string; weight: number }[] }[]; evidenceInputs?: EvidenceInput[] }
interface Variant { name: string; kind: string; key: string; value: number; nodeId?: string }
interface Experiment { id: string; status: string; manifestSha256: string; error?: string; request: { samples: number }; members: { name: string; runId: string; seed: number; configHash: string; parameterStep?: number | null }[] }
interface ExperimentReport { experiment: Experiment; runs: { id: string; status: string; progress?: { sampleCount: number; totalSamples: number } }[]; deltas: { variant: string; metric: string; baseline: number | null; observed: number | null; difference: number | null; derivative: number | null; interval: NumericInterval | null; suggestedSamplesPerArm: number | null; assumptions: string }[]; hypothesisFamilySize: number }
interface Atom { id: string; value: string; targetProbability: string; proposalProbability: string; stratum: string }
interface DesignEstimate { mean: number; standardError: number | null; interval: NumericInterval | null; exactReference: string }
interface SamplingReport { mode: string; samples: number; seed: number; targetSupportCovered: boolean; likelihoods: { id: string; target: string; proposal: string; weight: string; observed: number; stratum?: string | null; conditionalWeight?: string | null }[]; reward: DesignEstimate; tailProbability: DesignEstimate; exactEstimatorVariance: string; exactWeightSecondMoment: string; effectiveSampleSize: number | null; assumptions: string }
interface ResourceReport { stopProbability: string; retainedReward: string; referenceReward: string | null; omittedReward: string | null; retainedDuration: string; referenceStatus: string; horizon: number; assumptions: string }
interface ToolEvidence<T> { authoredInputSha256: string; report: T; retention?: { retained: boolean; detail?: string }; runtime: { coreBinarySha256: string } }
const number = (v: number | null | undefined) => formatNumber(v, 6);
const interval = (v: NumericInterval | null) => v ? `[${number(v.lower)}, ${number(v.upper)}]` : 'Withheld';
function download(name: string, value: unknown) { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function read<T>(path: string, signal: AbortSignal): Promise<T> {
  const response = await fetch(path, { signal: AbortSignal.any([signal, AbortSignal.timeout(15000)]) });
  const data = await response.json(); if (!response.ok) { if (response.status === 401) window.dispatchEvent(new Event('slotmath:auth-required')); throw new Error(data.error ?? `HTTP ${response.status}`); } return data;
}

/** Authored finite references and automatic pinned experiments share one evidence workspace.
 * Mutations are explicit, never automatically retried after ambiguous acceptance. */
export function VerificationWorkbench({ run }: { run: RunSnapshot }) {
  const [tab, setTab] = useState('experiments'), [graph, setGraph] = useState<GraphInput | null>(null), [error, setError] = useState('');
  useEffect(() => { const select = (event: Event) => { const value = (event as CustomEvent<string>).detail; if (['experiments', 'sampling', 'resource', 'inputs'].includes(value)) setTab(value); }; window.addEventListener('slotmath:verification-tab', select); return () => window.removeEventListener('slotmath:verification-tab', select); }, []);
  useEffect(() => {
    const abort = new AbortController();
    read<{ run: { id: string; configHash: string; configVersion: number }; pinnedConfig: GraphInput | null; inputVerified: boolean }>(`/api/runs/${encodeURIComponent(run.id)}/evidence`, abort.signal).then(e => {
      if (e.run?.id !== run.id || e.run.configHash !== run.configHash || e.run.configVersion !== run.configVersion || !e.pinnedConfig || !e.inputVerified) throw new Error('Pinned graph identity could not be verified.'); setGraph(e.pinnedConfig);
    }).catch(e => { if (!abort.signal.aborted) setError(e instanceof Error ? e.message : 'Pinned graph unavailable.'); });
    return () => abort.abort();
  }, [run.id, run.configHash, run.configVersion]);
  return <section className="simulation-card verification-workbench" id="verification-workbench" aria-label="Verification experiments"><div className="simulation-card-head"><div><h2>Verification experiments</h2><p>Compare declared models and policies. Every experiment pins its inputs before sampling.</p></div></div><div className="measurement-tabs" role="tablist">{[['experiments', 'Parameters & policies'], ['sampling', 'Verified sampling design'], ['resource', 'Resource-stop impact'], ['inputs', 'Rule / spec / asset evidence']].map(([id, label]) => <button className="btn" role="tab" aria-selected={tab === id} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>{error && <p role="alert">{error}</p>}
    {tab === 'experiments' && <ParameterExperiments run={run} graph={graph} />}
    {tab === 'sampling' && <SamplingDesign runId={run.id} />}
    {tab === 'resource' && <ResourceImpact runId={run.id} />}
    {tab === 'inputs' && <><p>These identities are part of the selected run's pinned graph, including any embedded bytes. SHA-256 matches content when embedded; external-only entries remain authored assertions.</p>{graph?.evidenceInputs?.length ? <div className="results-table-scroll"><table className="results-table"><thead><tr><th>Kind / ID</th><th>Version</th><th>SHA-256</th><th>Content</th></tr></thead><tbody>{graph.evidenceInputs.map(input => <tr key={`${input.kind}:${input.id}`}><td>{input.kind} / {input.id}</td><td>{input.version}</td><td><code>{input.sha256}</code></td><td>{input.contentBase64 ? 'Embedded, hash checked by compiler' : 'External identity only'}</td></tr>)}</tbody></table><button className="btn" onClick={() => download(`run-${run.id}-external-inputs.json`, graph.evidenceInputs)}>Export manifest and embedded inputs</button></div> : <p>No external input identities were pinned. Add them under Build → Data / AST → Rule / spec / asset inputs for the next run.</p>}</>}
  </section>;
}
function ParameterExperiments({ run, graph }: { run: RunSnapshot; graph: GraphInput | null }) {
  const [variants, setVariants] = useState<Variant[]>([]), [samples, setSamples] = useState(10000), [precision, setPrecision] = useState(.005), [confidence, setConfidence] = useState(.95);
  const [selectedMetrics, setSelectedMetrics] = useState<string[]>([]), [thresholds, setThresholds] = useState(''), [report, setReport] = useState<ExperimentReport | null>(null), [status, setStatus] = useState(''), [error, setError] = useState('');
  const [id, setId] = useState(() => sessionStorage.getItem(`slotmath:experiment:${run.id}`) ?? '');
  const operation = useRef<AbortController | null>(null);
  useEffect(() => () => operation.current?.abort(), []);
  useEffect(() => {
    if (!id) return; const abort = new AbortController(); let timer: ReturnType<typeof setTimeout> | undefined;
    const poll = async () => {
      try {
        const next = await read<ExperimentReport>(`/api/runs/experiments/${encodeURIComponent(id)}`, abort.signal);
        if (next.experiment.id !== id || !/^[a-f0-9]{64}$/.test(next.experiment.manifestSha256) || !Array.isArray(next.runs) || !Array.isArray(next.deltas)) throw new Error('Invalid experiment evidence.');
        setReport(next); setStatus(next.experiment.status); setError('');
        if (['pending', 'running'].includes(next.experiment.status)) timer = setTimeout(poll, document.hidden ? 10000 : 2000);
      } catch (e) { if (!abort.signal.aborted) { setError(`Read interrupted; recovering from the saved experiment: ${e instanceof Error ? e.message : 'network error'}`); timer = setTimeout(poll, 10000); } }
    }; void poll(); return () => { abort.abort(); if (timer) clearTimeout(timer); };
  }, [id]);
  const running = ['pending', 'running', 'Submitting…'].includes(status);
  const options = graph ? [
    ...Object.entries(graph.initialState ?? {}).filter(([, value]) => typeof value === 'number').map(([key, value]) => ({ name: `Initial state · ${key}`, kind: 'initialState', key, value: Number(value), nodeId: undefined })),
    ...graph.nodes.flatMap(node => node.nodeType === 'metricsSink' ? [{ name: `Win cap · ${node.label ?? node.id}`, kind: 'winCap', key: 'winCap', value: node.winCap ?? 1, nodeId: node.id }] : node.nodeType === 'loop' ? [{ name: `Loop limit · ${node.label ?? node.id}`, kind: 'loopCap', key: 'maxIterations', value: node.maxIterations ?? 1, nodeId: node.id }] : (node.drawWeights ?? []).map(w => ({ name: `Weight · ${node.label ?? node.id} · ${w.outcomeId}`, kind: 'drawWeight', key: w.outcomeId, value: w.weight, nodeId: node.id }))),
    ...(run.execution?.regime === 'sessions' ? ['initialBankroll', 'wager', 'stopThreshold', 'sessionLength'].map(key => ({ name: `Execution · ${key}`, kind: 'execution', key, value: Number((run.execution as unknown as Record<string, unknown>)[key] ?? (key === 'stopThreshold' ? 10 : 1)), nodeId: undefined })).concat(['fixedHorizon', 'ruin', 'profitTarget', 'lossLimit', 'featureFirst'].map(key => ({ name: `Session policy · ${key}`, kind: 'sessionPolicy', key, value: 10, nodeId: undefined }))) : [])
  ] : [];
  const metrics = [...(run.measurements ?? []).map(m => ({ id: m.id, name: m.name })), ...(run.execution?.regime === 'sessions' ? ['payoutPerTurnover', 'return', 'profit', 'ruin', 'duration', 'featureSeen', 'drawdown', 'extreme'].map(name => ({ id: `session.${name}`, name: `Session ${name}` })) : [])];
  const patch = (i: number, value: Partial<Variant>) => setVariants(v => v.map((row, j) => i === j ? { ...row, ...value } : row));
  async function submit() {
    operation.current?.abort(); const abort = new AbortController(); operation.current = abort; setError(''); setStatus('Submitting…');
    try {
      const tailThresholds = thresholds.trim() ? thresholds.split(',').map(t => Number(t.trim())) : [];
      if (tailThresholds.some(t => !Number.isFinite(t))) throw new Error('Tail thresholds must be finite. Configure the same thresholds on the selected measurements before running.');
      const request = { configId: run.configId, configVersion: run.configVersion, variants, measurements: run.measurements ?? [], execution: run.execution as ExecutionOptions | undefined, samples, seed: run.seed, confidence, precision, metricIds: selectedMetrics, tailThresholds };
      const accepted = await calculationRequest<Experiment>('/api/runs/experiments', request, abort.signal, setStatus);
      if (!accepted.id || !/^[a-f0-9]{64}$/.test(accepted.manifestSha256)) throw new Error('Accepted experiment identity is invalid. Refresh the archive before resubmitting.');
      sessionStorage.setItem(`slotmath:experiment:${run.id}`, accepted.id); setId(accepted.id); setStatus(accepted.status);
    } catch (e) { setStatus('Submission failed or acceptance unknown'); if (!abort.signal.aborted) setError(e instanceof Error ? e.message : 'Submission failed.'); }
  }
  return <div><p>Baseline: pinned graph v{run.configVersion}, seed {run.seed}. Each named variant changes one parameter and receives its own seed. Jobs execute sequentially within one five-minute experiment budget; at most eight variants and ten million total round slots.</p><fieldset disabled={running} className="measurement-form-grid"><label>Round slots per arm<input type="number" min="2" max="10000000" value={samples} onChange={e => setSamples(Number(e.target.value))} /></label><label>Desired difference precision<input type="number" min="0.00000001" step="any" value={precision} onChange={e => setPrecision(Number(e.target.value))} /></label><label>Confidence<input type="number" min="0.51" max="0.99999" step=".01" value={confidence} onChange={e => setConfidence(Number(e.target.value))} /></label><label>Comparison tail thresholds<input value={thresholds} onChange={e => setThresholds(e.target.value)} placeholder="1, 10, 100" /><small>Must already be tracked by selected metrics. Missing tails remain unavailable.</small></label></fieldset>
    <fieldset disabled={running}><legend>Additional comparison metrics · up to four</legend>{metrics.map(m => <label key={m.id}><input type="checkbox" checked={selectedMetrics.includes(m.id)} disabled={!selectedMetrics.includes(m.id) && selectedMetrics.length >= 4} onChange={e => setSelectedMetrics(v => e.target.checked ? [...v, m.id] : v.filter(id => id !== m.id))} />{m.name}</label>)}</fieldset>
    <fieldset disabled={running}><legend>Named perturbations / session policies</legend>{variants.map((v, i) => <div className="measurement-form-grid" key={i}><label>Name<input value={v.name} maxLength={80} onChange={e => patch(i, { name: e.target.value })} /></label><label>Parameter<select aria-label="Parameter" value={options.findIndex(o => o.kind === v.kind && o.key === v.key && o.nodeId === v.nodeId)} onChange={e => { const choice = options[Number(e.target.value)]; if (choice) patch(i, { kind: choice.kind, key: choice.key, value: choice.value, nodeId: choice.nodeId }); }}>{options.map((o, j) => <option key={j} value={j}>{o.name}</option>)}</select></label><label>{v.kind === 'sessionPolicy' ? 'Profit / loss threshold' : 'Perturbed value'}<input type="number" step="any" value={v.value} onChange={e => patch(i, { value: Number(e.target.value) })} /></label><button className="btn" onClick={() => setVariants(v => v.filter((_, j) => j !== i))}>Remove</button></div>)}<button className="btn" disabled={!options.length || variants.length >= 8} onClick={() => { const choice = options[0]; setVariants(v => [...v, { ...choice, name: `Variant ${v.length + 1}` }]); }}>Add variant</button></fieldset>
    <div className="measurement-actions"><button className="btn primary" disabled={running || !graph || !variants.length} onClick={() => void submit()}>Run pinned experiment</button>{running && id && <button className="btn" onClick={async () => { try { const response = await fetch(`/api/runs/experiments/${encodeURIComponent(id)}`, { method: 'DELETE' }); if (!response.ok) throw new Error(`Cancellation HTTP ${response.status}`); setStatus('Cancellation requested'); } catch(e) { setError(e instanceof Error ? e.message : 'Cancellation failed; poll saved state.'); } }}>Cancel experiment</button>}{status && <span role="status">{status}</span>}</div>{error && <p role="alert">{error}</p>}
    {report && <><p>Manifest SHA-256 <code>{report.experiment.manifestSha256}</code> · family size {report.hypothesisFamilySize}</p>{report.experiment.error && <p role="alert">{report.experiment.error}</p>}<div className="results-table-scroll"><table className="results-table"><thead><tr><th>Arm</th><th>Seed</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{report.experiment.members.map(m => { const child = report.runs.find(r => r.id === m.runId); return <tr key={m.runId}><td>{m.name}</td><td>{m.seed}</td><td>{child?.status ?? 'Unavailable'} · {child?.progress?.sampleCount ?? 0} observed rounds</td><td><a href={`/results?run=${m.runId}`}>Open result</a></td></tr>; })}</tbody></table><table className="results-table"><thead><tr><th>Variant / metric</th><th>Baseline</th><th>Observed</th><th>Delta</th><th>Sensitivity Δmetric/Δparameter</th><th>Difference interval</th><th>Planned samples per arm</th></tr></thead><tbody>{report.deltas.map(d => <tr key={`${d.variant}:${d.metric}`} title={d.assumptions}><td>{d.variant} / {d.metric}</td><td>{number(d.baseline)}</td><td>{number(d.observed)}</td><td>{number(d.difference)}</td><td>{number(d.derivative)}</td><td>{interval(d.interval)}</td><td>{number(d.suggestedSamplesPerArm)}</td></tr>)}</tbody></table></div><p>Intervals use independent-arm approximations with family allocation. Stopped or dependent rounds receive descriptive deltas; session payoutPerTurnover compares total payout / actual total external turnover with paired covariance; complete independent sessions can support session inference. Finite differences are local perturbations, not an analytic derivative or proof of model validity.</p><button className="btn" onClick={() => download(`experiment-${report.experiment.id}.json`, report)}>Export pinned experiment</button></>}
  </div>;
}
function SamplingDesign({ runId }: { runId: string }) {
  const [atoms, setAtoms] = useState<Atom[]>([]), [mode, setMode] = useState('importance'), [samples, setSamples] = useState(10000), [seed, setSeed] = useState(42), [threshold, setThreshold] = useState('1');
  const [allocations, setAllocations] = useState<Record<string, number>>({}), [report, setReport] = useState<ToolEvidence<SamplingReport> | null>(null), [status, setStatus] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const operation = useRef<AbortController | null>(null); useEffect(() => () => operation.current?.abort(), []);
  const groups = [...new Set(atoms.map(a => a.stratum))];
  async function calculate() {
    operation.current?.abort(); const abort = new AbortController(); operation.current = abort; setBusy(true); setError(''); setReport(null);
    try { setReport(await calculationRequest<ToolEvidence<SamplingReport>>(`/api/runs/measurements/sampling-design?runId=${encodeURIComponent(runId)}`, { atoms, mode, samples, seed, threshold, allocation: mode === 'stratified' ? groups.map(id => ({ id, samples: allocations[id] ?? 2 })) : null }, abort.signal, setStatus)); setStatus('Complete'); }
    catch(e) { if (!abort.signal.aborted) setError(e instanceof Error ? e.message : 'Design failed.'); } finally { setBusy(false); }
  }
  return <div><p>Supply a complete finite law. The server checks normalization and target support exactly, then actually samples from the proposal. This verifies the supplied design; arbitrary graph weight expressions are not certified by this calculation.</p><fieldset disabled={busy}><div className="measurement-form-grid"><label>Design<select value={mode} onChange={e => setMode(e.target.value)}><option value="importance">Ordinary importance estimate · p/q</option><option value="stratified">Fixed allocation · conditional p/q per stratum</option></select></label><label>Samples<input type="number" min="2" max="1000000" value={samples} onChange={e => setSamples(Number(e.target.value))} /></label><label>Seed<input type="number" value={seed} onChange={e => setSeed(Number(e.target.value))} /></label><label>Tail event: value ≥<input value={threshold} onChange={e => setThreshold(e.target.value)} /></label></div><div className="results-table-scroll"><table className="results-table"><thead><tr><th>Outcome ID</th><th>Payout</th><th>Target probability</th><th>Proposal probability</th><th>Stratum</th><th /></tr></thead><tbody>{atoms.map((atom, i) => <tr key={i}>{(['id', 'value', 'targetProbability', 'proposalProbability', 'stratum'] as const).map(key => <td key={key}><input aria-label={`Atom ${i + 1} ${key}`} value={atom[key]} onChange={e => setAtoms(rows => rows.map((a, j) => i === j ? { ...a, [key]: e.target.value } : a))} /></td>)}<td><button className="btn" onClick={() => setAtoms(a => a.filter((_, j) => j !== i))}>Remove</button></td></tr>)}</tbody></table></div><button className="btn" disabled={atoms.length >= 128} onClick={() => setAtoms(a => [...a, { id: `outcome-${a.length + 1}`, value: '0', targetProbability: '0', proposalProbability: '0', stratum: 'all' }])}>Add atom</button><button className="btn" onClick={() => setAtoms([{ id: 'loss', value: '0', targetProbability: '3/4', proposalProbability: '1/2', stratum: 'loss' }, { id: 'win', value: '4', targetProbability: '1/4', proposalProbability: '1/2', stratum: 'win' }])}>Load independent two-atom example</button>{mode === 'stratified' && groups.map(id => <label key={id}>Stratum {id} sample allocation<input type="number" min="2" value={allocations[id] ?? 2} onChange={e => setAllocations(a => ({ ...a, [id]: Number(e.target.value) }))} /></label>)}</fieldset><button className="btn primary" disabled={busy || !atoms.length} onClick={() => void calculate()}>Verify support and execute design</button>{status && <span role="status">{status}</span>}{error && <p role="alert">{error}</p>}
    {report && <><p>Input SHA-256 <code>{report.authoredInputSha256}</code></p><p>{report.report.assumptions}</p><dl className="tracked-statistics"><div><dt>Reward estimate / exact reference</dt><dd>{number(report.report.reward.mean)} / {report.report.reward.exactReference}</dd></div><div><dt>Reward interval</dt><dd>{interval(report.report.reward.interval)}</dd></div><div><dt>Tail probability / exact reference</dt><dd>{number(report.report.tailProbability.mean)} / {report.report.tailProbability.exactReference}</dd></div><div><dt>Tail interval</dt><dd>{interval(report.report.tailProbability.interval)}</dd></div><div><dt>Exact estimator variance</dt><dd>{report.report.exactEstimatorVariance}</dd></div><div><dt>Weight second moment / observed ESS</dt><dd>{report.report.exactWeightSecondMoment} / {number(report.report.effectiveSampleSize)}</dd></div></dl><div className="results-table-scroll"><table className="results-table"><thead><tr><th>ID</th><th>Target</th><th>Proposal</th><th>p/q</th><th>Observed</th></tr></thead><tbody>{report.report.likelihoods.map(a => <tr key={a.id}><td>{a.id}</td><td>{a.target}</td><td>{a.proposal}</td><td>{a.weight}{a.conditionalWeight && <small>Stratum {a.stratum}: conditional weight {a.conditionalWeight}</small>}</td><td>{a.observed}</td></tr>)}</tbody></table></div><button className="btn" onClick={() => download('verified-sampling-design.json', report)}>Export design evidence</button></>}
  </div>;
}
function ResourceImpact({ runId }: { runId: string }) {
  const [matrix, setMatrix] = useState<string[][]>([['1/2']]), [rewards, setRewards] = useState(['1']), [initial, setInitial] = useState(0), [horizon, setHorizon] = useState(10);
  const [report, setReport] = useState<ToolEvidence<ResourceReport> | null>(null), [status, setStatus] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const operation = useRef<AbortController | null>(null); useEffect(() => () => operation.current?.abort(), []);
  async function calculate() {
    operation.current?.abort(); const abort = new AbortController(); operation.current = abort; setBusy(true); setError(''); setReport(null);
    try { setReport(await calculationRequest<ToolEvidence<ResourceReport>>(`/api/runs/measurements/resource-impact?runId=${encodeURIComponent(runId)}`, { reference: { transientMatrix: matrix, rewards, initialState: initial }, horizon }, abort.signal, setStatus)); setStatus('Complete'); }
    catch(e) { if (!abort.signal.aborted) setError(e instanceof Error ? e.message : 'Comparison failed.'); } finally { setBusy(false); }
  }
  return <div><p>Build the uncapped feature reference as a finite substochastic Markov model. Missing row mass is absorption. Rewards are paid before each transition. Exact omitted reward is available only when the reference has a finite expected reward; a runtime timeout alone cannot determine it.</p><fieldset disabled={busy}><div className="measurement-form-grid"><label>Feature step budget<input type="number" min="1" max="4096" value={horizon} onChange={e => setHorizon(Number(e.target.value))} /></label><label>Initial state<select value={initial} onChange={e => setInitial(Number(e.target.value))}>{rewards.map((_, i) => <option key={i} value={i}>State {i}</option>)}</select></label></div><div className="results-table-scroll"><table className="results-table"><thead><tr><th>From state</th>{rewards.map((_, i) => <th key={i}>To {i}</th>)}<th>Reward per visit</th></tr></thead><tbody>{matrix.map((row, i) => <tr key={i}><td>{i}</td>{row.map((p, j) => <td key={j}><input aria-label={`Transition ${i} to ${j}`} value={p} onChange={e => setMatrix(m => m.map((r, k) => k === i ? r.map((v, l) => l === j ? e.target.value : v) : r))} /></td>)}<td><input aria-label={`State ${i} reward`} value={rewards[i]} onChange={e => setRewards(r => r.map((v, j) => j === i ? e.target.value : v))} /></td></tr>)}</tbody></table></div><button className="btn" disabled={rewards.length >= 8} onClick={() => { setMatrix(m => [...m.map(row => [...row, '0']), Array<string>(m.length + 1).fill('0')]); setRewards(r => [...r, '0']); }}>Add state</button></fieldset><button className="btn primary" disabled={busy} onClick={() => void calculate()}>Compare bounded and uncapped reference</button>{status && <span role="status">{status}</span>}{error && <p role="alert">{error}</p>}
    {report && <><p>Input SHA-256 <code>{report.authoredInputSha256}</code></p><p>{report.report.assumptions}</p><dl className="tracked-statistics">{[['Probability of requiring a step past the limit', report.report.stopProbability], ['Retained expected reward', report.report.retainedReward], ['Uncapped expected reward', report.report.referenceReward ?? 'Undefined'], ['Omitted expected reward', report.report.omittedReward ?? 'Withheld'], ['Bounded expected duration', report.report.retainedDuration], ['Reference status', report.report.referenceStatus]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><button className="btn" onClick={() => download('resource-stop-reference.json', report)}>Export resource-impact evidence</button></>}
  </div>;
}
