import { test, expect, getWithQuota } from './fixtures';

test.beforeEach(async ({ request }) => {
  test.setTimeout(120000);
  const response = await request.get('/api/auth/status');
  if (response.status() === 429) await new Promise(resolve => setTimeout(resolve, Math.min(60000, Math.max(1000, Number(response.headers()['retry-after'] ?? '1') * 1000))));
});
test('Authored episode, grouped distribution, reference verdict, WebSocket evidence and reload agree', async ({ page }) => {
  const frames: Record<string, unknown>[] = [];
  page.on('websocket', socket => socket.on('framereceived', ({ payload }) => { for (const frame of String(payload).split('\x1e')) { try { const message = JSON.parse(frame); if (message.target === 'ProgressUpdate') frames.push(message.arguments[0]); } catch { /* handshake */ } } }));
  await page.goto('/build'); await page.getByLabel('Import project file').setInputFiles('e2e/fixtures/measurement-model.json');
  await page.getByRole('tab', { name: 'Simulate', exact: true }).click(); await page.getByRole('button', { name: '＋ Track metric', exact: true }).click();
  await page.getByLabel('Metric name').fill('Sticky episode total'); await page.getByLabel('Metric observation level').selectOption('node'); await page.getByLabel('Metric graph node').selectOption('end');
  await page.getByLabel('Enable advanced measurement').check(); await page.getByLabel('Measurement subject', { exact: true }).selectOption('episode'); await page.getByLabel('Episode entry', { exact: true }).selectOption('fs'); await page.getByLabel('Episode exit', { exact: true }).selectOption('sink');
  await page.getByLabel('Metric numeric expression').fill('state.spinWin'); await page.getByLabel('Metric unit').fill('coins'); await page.getByLabel('Metric filter mode').selectOption('expression'); await page.getByLabel('Metric filter expression').fill('state.fsType == "sticky"');
  await page.getByText('Group, pair and award accounting', { exact: true }).click(); await page.getByLabel('Group / cohort key', { exact: true }).fill('"sticky"');
  await page.getByLabel('Paired value / wager denominator', { exact: true }).fill('1');
  await page.getByText('Uncertainty, precision and reference checks', { exact: true }).click(); await page.getByLabel('Independent measurement subjects').check();
  await page.getByRole('button', { name: 'Add reference outcome', exact: true }).click(); await page.getByLabel('Reference outcome 1', { exact: true }).fill('6'); await page.getByLabel('Reference probability 1', { exact: true }).fill('1');
  await page.getByLabel('Reference mean', { exact: true }).fill('6'); await page.getByLabel('Acceptance tolerance', { exact: true }).fill('0.01'); await page.getByLabel('Proven minimum', { exact: true }).fill('6'); await page.getByLabel('Proven maximum', { exact: true }).fill('6');
  await page.getByRole('button', { name: 'Save measurement', exact: true }).click(); await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByLabel('Simulation spins').fill('5000'); const launch = page.waitForResponse(r => r.url().endsWith('/api/runs') && r.request().method() === 'POST'); await page.getByRole('button', { name: /^▶ Start run$/ }).click(); const created = await (await launch).json();
  await expect(page.locator('.run-status')).toHaveText('completed', { timeout: 70000 }); const card = page.getByRole('article', { name: 'Tracked metric Sticky episode total', exact: true });
  await expect(card.locator('[data-statistic=mean]')).toHaveText('6 coins'); await expect(card).toContainText('Complete feature episodes'); await expect(card.getByRole('img', { name: 'frequency by payout band' })).toBeVisible();
  await card.getByRole('tab', { name: 'uncertainty', exact: true }).click(); await expect(card).toContainText('within Precision'); await expect(card).toContainText('[6, 6]');
  const evidence = await (await getWithQuota(page.request, `/api/runs/${created.id}/evidence`)).json(); const measurement = evidence.run.progress.measurements[0];
  expect(measurement.count).toBe(5000); expect(measurement.analysis.entries).toBe(5000); expect(measurement.analysis.exits).toBe(5000); expect(measurement.analysis.support).toEqual([{ value: 6, count: 5000, sum: 30000 }]); expect(measurement.analysis.checks[0].status).toBe('withinPrecision');
  expect(measurement.analysis.groups.sticky.mean).toBe(6); expect(measurement.analysis.groups.sticky.count).toBe(5000);
  expect(frames.some(f => Array.isArray(f.measurements) && (f.measurements as { analysis?: unknown }[])[0]?.analysis)).toBeTruthy();
  await card.locator('.measurement-witnesses > summary').click(); await card.getByRole('button', { name: /Replay first witness/ }).click(); await expect(card.getByLabel('Reconstructed witness')).toContainText('logical stream prefix', { timeout: 70000 });
  await card.locator('.measurement-calibration > summary').click(); await card.getByRole('button', { name: 'Calibrate pinned distribution', exact: true }).click(); await expect(card.getByLabel(`Calibrated distribution for ${measurement.id}`)).toContainText('p-value 1.00000', { timeout: 70000 });
  await page.locator('.graph-measurement-reference > summary').click(); await page.getByRole('button', { name: 'Enumerate pinned measurements', exact: true }).click(); await expect(page.getByLabel('Pinned graph enumeration result')).toContainText('Conditional means are withheld', { timeout: 70000 });
  const enumeration = page.getByLabel('Pinned graph enumeration result');
  await enumeration.getByText('Sticky episode total · probability support', { exact: true }).click();
  await enumeration.getByText('Paired joint law · complete', { exact: true }).first().click();
  await expect(enumeration).toContainText('conditional means X / Y 6/1 / 2/1');
  await enumeration.getByText('Cohort sticky · complete value law', { exact: true }).click();
  await expect(enumeration).toContainText('Expected valid subjects / round 1/1');
  const retained = await (await getWithQuota(page.request, `/api/runs/${created.id}/evidence`)).json();
  expect(retained.diagnostics.map((d: { kind: string }) => d.kind).sort()).toEqual(['discrete-calibration', 'graph-enumeration', 'witness-replay']);
  expect(retained.diagnostics.every((d: { inputSha256: string; outputSha256: string }) => /^[a-f0-9]{64}$/.test(d.inputSha256) && /^[a-f0-9]{64}$/.test(d.outputSha256))).toBe(true);
  await page.goto(`/simulate?run=${created.id}`); await expect(page.getByRole('article', { name: 'Tracked metric Sticky episode total', exact: true }).locator('[data-statistic=mean]')).toHaveText('6 coins');
  await page.goto(`/results?run=${created.id}`); await expect(page.getByRole('heading', { name: 'Sticky episode total · saved analysis', exact: true })).toBeVisible({ timeout: 70000 });
});
test('Native reference workbench proves equal-RTP moments and rejects a closed feature state', async ({ page }) => {
  await page.goto('/simulate'); await page.getByText('Independent reference workbench', { exact: true }).click();
  await page.getByRole('button', { name: 'Calculate exact reference', exact: true }).click(); const result = page.getByLabel('Reference calculation result');
  await expect(result).toContainText('49/50'); await expect(result).toContainText('2401/2500');
  await page.getByLabel('Reference model type').selectOption('markov'); await page.getByRole('button', { name: 'Calculate exact reference', exact: true }).click();
  await expect(result).toContainText('Expected duration 3/1'); await expect(result).toContainText('expected reward 6/1');
  await page.getByLabel('Transition 1 to 1').fill('1'); await page.getByRole('button', { name: 'Calculate exact reference', exact: true }).click();
  await expect(result).toContainText('nonterminating'); await expect(result).toContainText('expected reward undefined');
  await page.getByLabel('Reference model type').selectOption('stationary'); await page.getByRole('button', { name: 'Load independent example', exact: true }).click(); await page.getByRole('button', { name: 'Calculate exact reference', exact: true }).click(); await expect(result).toContainText('long-run'); await expect(result).toContainText('49/50');
  await page.locator('#sample-planning > summary').click(); await page.getByRole('button', { name: 'Calculate observation budget', exact: true }).click(); await expect(page.getByLabel('Observation planning result')).toContainText('29,957,322'); await expect(page.getByLabel('Observation planning result')).toContainText('detection budget: insufficient');
});
test('Catalogue recipe becomes a visual Boolean AST and fixed-horizon session evidence survives reload', async ({ page }) => {
  await page.goto('/build'); await page.getByLabel('Import project file').setInputFiles('e2e/fixtures/measurement-model.json');
  await page.getByRole('tab', { name: 'Simulate', exact: true }).click();
  await page.locator('#metric-catalogue > summary').click(); await page.getByLabel('Search metric catalogue').fill('zero-payout');
  await page.getByRole('button', { name: /^Zero-payout probability/ }).click(); await page.getByRole('button', { name: 'Configure measurement →', exact: true }).click();
  await page.getByLabel('Metric name').fill('Zero payout'); await page.getByLabel('Metric value source').selectOption('visual');
  await expect(page.getByLabel('Metric value node type', { exact: true })).toHaveValue('compare');
  await page.getByLabel('Metric value Left namespace', { exact: true }).selectOption('measurement');
  await page.getByRole('button', { name: 'Save measurement', exact: true }).click(); await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.locator('#execution-configuration > summary').click(); await page.getByLabel('Execution regime').selectOption('sessions');
  await page.getByLabel('Session horizon').fill('10'); await page.getByLabel('Session bankroll').fill('3'); await page.getByLabel('Session feature activation').selectOption({ label: 'Zero payout' });
  await page.getByLabel('Simulation spins').fill('1000');
  const launch = page.waitForResponse(r => r.url().endsWith('/api/runs') && r.request().method() === 'POST'); await page.getByRole('button', { name: /^▶ Start run$/ }).click(); const created = await (await launch).json();
  await expect(page.locator('.run-status')).toHaveText('completed', { timeout: 70000 });
  const evidence = await (await getWithQuota(page.request, `/api/runs/${created.id}/evidence`)).json();
  expect(evidence.run.execution.regime).toBe('sessions'); expect(evidence.run.streamScheme).toBe('splitmix64-session-v1-10');
  const summary = evidence.run.progress.execution, metrics = Object.fromEntries(summary.sessionMetrics.map((m: { id: string }) => [m.id, m]));
  expect(summary.completedSessions).toBe(100); expect(summary.attemptedRounds).toBe(1000); expect(summary.interruptedRounds).toBe(0);
  expect(summary.monetaryAccounting).toBe('decimal-roundtrip-v1');
  expect(metrics['session.ruin'].mean).toBe(1); expect(metrics['session.ruinTime'].mean).toBe(3); expect(metrics['session.featureWait'].mean).toBe(1);
  expect(evidence.run.runtimeProvenance.coreBinarySha256).toMatch(/^[a-f0-9]{64}$/);
  await expect(page.locator('.simulation-heading')).toContainText('independent sessions of 10 paid rounds');
  await page.locator('.loop-termination-evidence > summary').click(); await expect(page.getByRole('row', { name: /fs 1,000 0 1,000/ })).toBeVisible();
  await page.reload(); await expect(page.getByLabel('Execution and session evidence')).toContainText('First feature wait');
  await page.goto(`/results?run=${created.id}`); await expect(page.getByLabel('Execution and session evidence')).toContainText('Maximum drawdown', { timeout: 70000 });
});
test('An authored rule assertion retains exact failure counts and a replayable violation through saved results', async ({ page }) => {
  await page.goto('/build'); await page.getByLabel('Import project file').setInputFiles('e2e/fixtures/measurement-model.json');
  await page.getByRole('tab', { name: 'Simulate', exact: true }).click(); await page.getByRole('button', { name: '＋ Track metric', exact: true }).click();
  await page.getByLabel('Metric name').fill('Reveal rule residual'); await page.getByLabel('Metric observation level').selectOption('node');
  await page.getByLabel('Metric graph node').selectOption('end'); await page.getByLabel('Enable advanced measurement').check();
  await page.getByLabel('Measurement source', { exact: true }).selectOption('event'); await page.getByLabel('Metric numeric expression').fill('state.spinWin != 3');
  await page.getByLabel('Assert exactly zero or false').check(); await page.getByRole('button', { name: 'Save measurement', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible(); await page.getByLabel('Simulation spins').fill('100');
  const launch = page.waitForResponse(r => r.url().endsWith('/api/runs') && r.request().method() === 'POST' && r.ok(), { timeout: 70000 });
  await page.getByRole('button', { name: /^▶ Start run$/ }).click(); const created = await (await launch).json();
  await expect(page.locator('.run-status')).toHaveText('completed', { timeout: 70000 });
  const card = page.getByRole('article', { name: 'Tracked metric Reveal rule residual', exact: true });
  await expect(card).toContainText('200 violations / 300 checked');
  await card.locator('.measurement-witnesses > summary').click(); await card.getByRole('button', { name: /Replay assertionViolation witness/ }).click();
  await expect(card.getByLabel('Reconstructed witness')).toContainText('assertionViolation', { timeout: 70000 });
  const evidence = await (await getWithQuota(page.request, `/api/runs/${created.id}/evidence`)).json();
  expect(evidence.run.progress.measurements[0].analysis.assertion).toEqual({ kind: 'zero', checked: 300, violations: 200, status: 'discrepancy' });
  expect(evidence.diagnostics.some((d: { kind: string }) => d.kind === 'witness-replay')).toBe(true);
  await page.locator('#reference-workbench > summary').click(); await page.locator('#exact-law-comparison > summary').click();
  await page.getByRole('button', { name: 'Compare exact laws', exact: true }).click();
  const comparison = page.getByLabel('Exact law comparison result'); await expect(comparison).toContainText('Supplied laws differ', { timeout: 70000 });
  await expect(comparison).toContainText('Left / right mean 49/50 / 49/50'); await expect(comparison).toContainText('Exact total variation 1/2');
  const retained = await (await getWithQuota(page.request, `/api/runs/${created.id}/evidence`)).json();
  expect(retained.diagnostics.some((d: { kind: string }) => d.kind === 'independent-law-comparison')).toBe(true);
  await page.goto(`/results?run=${created.id}`); await expect(page.getByText(/200 violations \/ 300 checked/)).toBeVisible({ timeout: 70000 });
});
