import { test, expect, getWithQuota } from './fixtures';

test('Native charts select counts and higher moments, retain them after reload and keep empty means undefined', async ({ page }) => {
  test.setTimeout(180000);
  await page.goto('/build'); await page.getByLabel('Import project file').setInputFiles('e2e/fixtures/measurement-model.json');
  await page.getByRole('tab', { name: 'Simulate', exact: true }).click();
  await page.getByRole('button', { name: '＋ Track metric', exact: true }).click();
  await page.getByLabel('Metric name').fill('Sticky scalar trends'); await page.getByLabel('Metric unit').fill('coins');
  await page.getByLabel('Metric observation level').selectOption('node'); await page.getByLabel('Metric graph node').selectOption('end');
  await page.getByLabel('Metric numeric expression').fill('state.spinWin'); await page.getByLabel('Enable advanced measurement').check();
  await page.getByLabel('Metric filter mode').selectOption('expression'); await page.getByLabel('Metric filter expression').fill('state.fsType == "sticky"');
  await page.getByLabel('Metric chart statistic', { exact: true }).selectOption('max');
  await page.getByRole('button', { name: 'Save measurement', exact: true }).click(); await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: '＋ Track metric', exact: true }).click();
  await page.getByLabel('Metric name').fill('Empty scope trend'); await page.getByLabel('Metric filter mode').selectOption('expression'); await page.getByLabel('Metric filter expression').fill('false');
  await page.getByLabel('Metric chart statistic', { exact: true }).selectOption('count');
  await page.getByRole('button', { name: 'Save measurement', exact: true }).click(); await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByLabel('Simulation spins').fill('5000');
  const launch = page.waitForResponse(r => r.url().endsWith('/api/runs') && r.request().method() === 'POST' && r.ok(), { timeout: 70000 });
  await page.getByRole('button', { name: /^▶ Start run$/ }).click(); const run = await (await launch).json();
  await expect(page.locator('.run-status')).toHaveText('completed', { timeout: 70000 });
  const card = page.getByRole('article', { name: 'Tracked metric Sticky scalar trends', exact: true }), chart = card.locator('.measurement-plot');
  const selector = card.getByLabel('Chart statistic for Sticky scalar trends', { exact: true });
  await expect(chart.locator('.plot-readout strong')).toHaveText('Maximum 4 coins');
  await selector.selectOption('distinctParents'); await expect(chart.locator('.plot-readout strong')).toHaveText('Paid rounds with matching children 5,000');
  await selector.selectOption('count'); await expect(chart.locator('.plot-readout strong')).toHaveText('Matching count 10,000');
  await selector.selectOption('sampleVariance'); await expect(chart.locator('.plot-readout strong')).toHaveText('Sample variance 1.0001 (coins)²');
  await expect(card.locator('[data-statistic=mean]')).toHaveText('3 coins');
  await expect(page.getByText('The saved run keeps its original collection plan.', { exact: false })).not.toBeVisible();
  const evidence = await (await getWithQuota(page.request, `/api/runs/${run.id}`)).json(); expect(evidence.measurementHash).toBe(run.measurementHash);
  // Independent law: each paid round includes exactly one 2 and one 4.
  expect(evidence.progress.measurements[0]).toMatchObject({ observations: 15000, count: 10000, excluded: 5000, mean: 3 });
  expect(evidence.progress.measurements[0].analysis.moments.sampleVariance).toBeCloseTo(10000 / 9999, 10);
  await page.reload(); await expect(selector).toHaveValue('sampleVariance'); await expect(chart.locator('.plot-readout strong')).toHaveText('Sample variance 1.0001 (coins)²');
  const stored = JSON.parse(await page.evaluate(() => localStorage.getItem('slotmath-simulation-v2')!));
  expect(stored.points.at(-1).measurements[0].statistics).toMatchObject({ distinctParents: 5000, count: 10000, secondMoment: 10 });
  expect(stored.points.at(-1).measurements[0].analysis).toBeUndefined();
  const empty = page.getByRole('article', { name: 'Tracked metric Empty scope trend', exact: true });
  await expect(empty.locator('.plot-readout strong')).toHaveText('Matching count 0'); await expect(empty.locator('.plot-dot')).toHaveCount(1);
  await empty.getByLabel('Chart statistic for Empty scope trend', { exact: true }).selectOption('mean');
  await expect(empty.locator('.plot-readout strong')).toHaveText('Average —'); await expect(empty.locator('.plot-dot')).toHaveCount(0);
  await expect(empty.locator('.plot-empty')).toHaveText('No defined values for this statistic');
  await chart.getByRole('img').focus(); await page.keyboard.press('Home'); await page.keyboard.press('End');
  await expect(chart.locator('.plot-readout strong')).toHaveText('Sample variance 1.0001 (coins)²');
  await page.setViewportSize({ width: 390, height: 844 }); await selector.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(selector).toBeVisible();
  await expect.poll(() => chart.getByRole('img').evaluate((svg: SVGSVGElement) => svg.getScreenCTM()!.a * parseFloat(getComputedStyle(svg.querySelector('.plot-label')!).fontSize))).toBeGreaterThanOrEqual(9.5);
  await page.screenshot({ path: '../docs/verification/measurement-trends-mobile.png', fullPage: true });
});
